### ISSUE TITLE
Markdown Relative Link - PDF Files

### ISSUE THREAD

**Issue by DeanWhitehouse** [nuxt/content#1013]
Our markdown contains a link to a PDF that is in the static content folder, however because it's relative the system converts it to a `nuxt-link` and then doesn't work.

I can see it's documented https://content.nuxtjs.org/writing#links but can't see anyway around this automatic conversion, any guidance would be appreciated

**Comment by Tahul** [comment]
Hey :)

This is now handled natively by NuxtLink thanks to https://github.com/nuxt/framework/pull/3659

This should so be fixed in v2.

Fixing this in v1 won't be a part of the @nuxt/content roadmap.

I'm closing this issue but feel free to reopen with a PR targeted at `v1` branch if you manage to fix this in that version!

**Comment by DeanWhitehouse** [comment]
Hey @Tahul,

Taking a look at https://github.com/nuxt/framework/pull/3659 I don't see how this relates, as the link isn't an external link - or are you saying that I need to raise a PR on nuxt/framework?
