### ISSUE TITLE
Image is not loaded if the image name contains space

### ISSUE THREAD

**Issue by axelthat2** [nuxt/content#1016]
### Version
@nuxt/content: ^1.14.0
nuxt: ^2.15.7

### Reproduction Link
https://github.com/axelthat2/nuxt-c-bug2

### Steps to reproduce
1. `git clone https://github.com/axelthat2/nuxt-c-bug2`
2. `yarn dev`

### What is Expected?
For the image to load.

### What is actually happening?
I get this instead `This is a markdown content. ![Image](/test image.png)`. This only happens if the image file contains space. Using `/test%20image.png` works.

**Comment by Tahul** [comment]
Hello @axelthat2 ; I would say this is the expected behavior.

Even if your browser might (but shouldn't) display the URL with a space, spaces in URLs are never correct.

I would recommend not using space in file names in general, especially when they are piped through different processing steps like it is the case with @nuxt/content.

I am closing this for now, but feel free to re-open with an according PR targeted at `v1` branch if you wish to fix this.
