### ISSUE TITLE
Provide reading time for content

### ISSUE THREAD

**Issue by Mokkapps** [nuxt/content#1231]
### Is your feature request related to a problem? Please describe
I use Nuxt Content for my blog and I want to show the reading time above each blog post.

### Describe the solution you'd like
It would be nice if we could have a new property like `timeToRead` if we query content 

### Describe alternatives you've considered
Alternatively, you could tell me how I can implement this with Nuxt v2 content without this new property :-) 

### Additional context
How it can be solved in Gatsby: [gatsby-remark-reading-time](https://www.gatsbyjs.com/plugins/gatsby-remark-reading-time/)

**Comment by NozomuIkuta** [comment]
[remark-reading-time](https://www.npmjs.com/package/remark-reading-time) will be what you are looking for in non-Gatsby context.

Both of them seem to depend on the same package to calculate time to read: [reading-time](https://github.com/ngryman/reading-time).

You can add a remark plugin like below:

```typescript
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  modules: ['@nuxt/content'],
  content: {
    markdown: {
      remarkPlugins: ['remark-reading-time'],
    },
  },
});
```

Ref. https://content.nuxtjs.org/api/configuration#markdown

---

By the way, IMO, this kind of feature should be kept as a user-configured plugin rather than implementing as one of default plugins, because calculating time to read is not essential to Nuxt Conent's functionalities: store, fetch, and render data.

**Comment by Mokkapps** [comment]
Thanks @NozomuIkuta !

Unfortunately, I cannot see the reading time at the queried content after adding the plugin, see this example: https://stackblitz.com/edit/github-1ujfy4?file=pages/[...slug].vue

What am I doing wrong?

**Comment by farnabaz** [comment]
@Mokkapps  I think you've missed the generated `readingTime` field in the document. You did everything right and when I open your link in my browser I can see generated `readingTime`. Here is the generated time for the index file

```
"readingTime": {
    "text": "1 min read",
    "minutes": 0.205,
    "time": 12300,
    "words": 41
  },
```

**Comment by Mokkapps** [comment]
You are right, I close this issue. Thanks @farnabaz  and @NozomuIkuta !
