### ISSUE TITLE
Can specify a port of the dev ws

### ISSUE THREAD

**Issue by guille-moe** [nuxt/content#1244]
### Is your feature request related to a problem? Please describe
The `4000` port is used by Nuxt Content v2 when I start a Nuxt dev server which can be already in use or require a port forwarding (both in my case).
There is no hint anywhere that Nuxt Content need a port to work.

### Describe the solution you'd like
Can specify a port number in the `content` Nuxt config object.

### Describe alternatives you've considered
For now I shutdown my other project which use `4000` and map the port `4000` of the docker container running the Nuxt dev server.

### Additional context
https://github.com/nuxt/content/blob/main/src/module.ts#L419

I am not so sure what this imply but I guess I can try work on this to do a PR to add a `port` in `ModuleOptions` with a default to `4000` to specify the port for Listhen.
Tell me what kind of change will be relevant, I can try to implement something.

**Comment by NozomuIkuta** [comment]
@guille-moe 

Although I'm not so familiar with the current implementation, here are some information for you.
I hope these information helps you somehow.

---

Goal: Add option(s) to have a control on Nuxt Content's WebSocket server

First, you need to change interface of the module options.

https://github.com/nuxt/content/blob/8cab2972813919f6eb9d7ffda36a10e1ea987bda/src/module.ts#L38-L161

When you add new options, it's better to check type definition of [unjs/listhen](https://github.com/unjs/listhen)'s `listen` function, to which options that you are adding are supposed to be passed.

Second, you need to define the default value(s) for the options.

https://github.com/nuxt/content/blob/8cab2972813919f6eb9d7ffda36a10e1ea987bda/src/module.ts#L181-L197

Third, as you described, change the call of `listen` function.

https://github.com/nuxt/content/blob/8cab2972813919f6eb9d7ffda36a10e1ea987bda/src/module.ts#L419

You may need to add a unit test in `test` directory.

https://github.com/nuxt/content/tree/main/test

---

By the way, since Nuxt Content v2 have already reached to stable version, design of option schema should be well-designed  for it not to be legacy (generally, no breaking change are supposed to be made while its major version is same). 

You could start to develop a PR for demonstration, or might want to get feedback from the authors and other people in the community about design before creating a PR.

--- 

I will post another message if I come up with an idea.
