### ISSUE TITLE
Code Highlighting in Content v2

### ISSUE THREAD

**Issue by Hystersis** [nuxt/content#1421]
I've been trying to use code highlighting in Nuxt Content v2. For example:
```
```js{1}[file_name]
export default () => {
  console.log('Code block')
}
``` ​
```
Content doesn't seem to be adding any classes (like seen in the Nuxt documentation) for easy styling. In addition, Content doesn't seem to add the `file_name` to the HTML, so how would add and style that? Also, how do you recommend background styling to align with the set Shiki theme?

**Comment by farnabaz** [comment]
Have you used [`highlight`](https://content.nuxtjs.org/api/configuration/#highlight) in content options? By default code highlighting is disabled, and you need to enable it.

**Comment by Hystersis** [comment]
Hi @farnabaz , I've enabled code highlighting with: ```
export default defineNuxtConfig({
  content: {
    highlight: {
      theme: 'github-light'
    }
  }
})

```
I'll have a look at reproducing it.

**Comment by Hystersis** [comment]
I've reproduced it in StackBlitz, even though a file name is specified with `[file_name]` it doesn't appear in the DOM. Have a look using the inspect tool, Content doesn't seem to be adding any classes to the DOM nor `file_name`.
https://stackblitz.com/edit/github-ahj78t-z4gqlj?file=content/index.md

**Comment by farnabaz** [comment]
Sorry for the late response,
By default `ProseCode` does not show filename, in order to customize the design and add extra information like filename, you need to override `ProseCode` in your project and create your magic.

All you need is to create `ProseCode.vue` inside `components/content/` directory. Take a look at default [`ProseCode` component source](https://github.com/nuxt/content/blob/main/src/runtime/components/Prose/ProseCode.vue).
