### ISSUE TITLE
[Docs] Footer icons are partially broken

### ISSUE THREAD

**Issue by manniL** [nuxt/content#1475]
### Reproduction

1. Check https://content.nuxtjs.org/ in Chrome
2. See that icons froms NuxtJS and Vue Telescope are missing

---

1. Check https://content.nuxtjs.org/ in Firefox
2. See below
![grafik](https://user-images.githubusercontent.com/640208/186387612-ee36be2a-c983-4f7b-ab48-dc3393f24ede.png)

### Describe the bug

The icons should be there and have acceptable width.
Just set `w-6 h-6` as classes 😋 

Would create a PR but it seems it is a Docus theme topic and the repo is still private.

Related: https://github.com/nuxt/content/issues/1419

**Comment by nobkd** [comment]
Yeah, but I would suggest to use `w-5 h-5` because the other social icons are using those too. The view box of the svg icons is not optimal, so they seem smaller when using the same style classes.

I commented this already in [this (closed) issue](https://github.com/nuxt/content/issues/1419#issuecomment-1222306807)

**Comment by manniL** [comment]
Oh, missed that issue!
Yes, I was thinking about `w-6 h-6` too but then they look quite different from the rest.
