### ISSUE TITLE
Search field weight

### ISSUE THREAD

**Issue by alexgrozav** [nuxt/content#170]
### Is your feature request related to a problem? Please describe.
The current full text search implementation does not provide a way to set the weight of the search field. Usually you'll want the search weight to be `title ~1 > description ~0.75 > text ~0.5`. This way the results will be ordered by importance for similar pages. 

### Describe the solution you'd like
Something similar to the following configuration should be possible:

~~~js
content: {
    fullTextSearchFields: [
        { field: 'title', weight: 1 },
        { field: 'description', weight: 0.75 },
        { field: 'text', weight: 0.5 }
    ]
}
~~~

### Describe alternatives you've considered
Until now I've been using [Fuse.js](https://fusejs.io) for searching in my documentation. It's an excellent fuzzy search implementation. Perhaps you could look into integrating it.

**Comment by benjamincanac** [comment]
Hey @alexgrozav,

Indeed it would be really cool to have this feature, however we're depending on [LokiDB](https://github.com/LokiJS-Forge/LokiDB#readme) and its [full-text-search plugin](https://www.npmjs.com/package/@lokidb/full-text-search) which doesn't seem to support this.

I don't see how we could migrate from the full-text-search plugin to fuse.js while keeping LokiDB because of query chaining.

If you have any idea, PRs are more than welcome!

**Comment by Atinux** [comment]
Sadly we won't be able to implement this feature for Content v1, we will think of this for a major release.

Thanks @alexgrozav for your feedback :)
