### ISSUE TITLE
Content passed to slots is rendered multiple times

### ISSUE THREAD

**Issue by eliaSchenker** [nuxt/content#1985]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.5.2`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-syrfpd-jmspgd?file=content/index.md

The issue is immediately visible when running, the 'My Button' and 'Some keywords' are rendered multiple times.

### Describe the bug

I have a simple component with multiple slot inputs (see reproduction). One of the slots (button) is passed to another component. For some reason two of the four slots seem to be rendered two times.
![image](https://user-images.githubusercontent.com/78470999/228851295-57652512-eca0-4127-95df-2f1a90622305.png)
There also seems to be some rogue elements, which seem to appear almost randomly:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/78470999/228852074-c4888909-f4a7-49a3-821e-4f61176486d6.png">

This can be very easily reproduced as the reproduction shows by passing multiple slots to a component.

The bug seems to also only occurr if we have another component with as slot and pass the contentslot down into that component (button in the reproduction)

**Comment by nobkd** [comment]
Your example creates a **hydration mismatch** because you use `<ContentSlot>` inside a `<p>` without using `unwrap` or `unwrap="p"`.

Seems like Nuxt or Vue doesn't like it if you do this, as it somehow breaks the HTML structure:

```vue
<p>
  <p>Text</p>
</p>
```

See this comment: https://github.com/nuxt/content/issues/1537#issuecomment-1250810387

In conclusion, you have three ways to fix your issue:
1. add an `unwrap` or `unwrap="p"` attribute to the `<ContentSlot>`s in `<p>`s
2. remove the `<p>`s around `description` and `keywords` slots
3. if you don't need markdown styling for a slot, you can use `<slot name="slotname" />` for completely raw text

Even though that fixes the issue, you should consider, to do this for the other two slots too, as they render unnecessary `<p>`s inside `<button>` or `<h2>` tags

**Comment by nobkd** [comment]
This could be your component:

```vue
<!-- components/content/test-component.vue -->

<template>
  <section>

    <h2>
      <ContentSlot :use="$slots.title" unwrap="p" />
    </h2>

    <ContentSlot :use="$slots.description" />
    <ContentSlot :use="$slots.keywords" />

    <base-button>
      <ContentSlot :use="$slots.button" unwrap="p" />
    </base-button>

  </section>
</template>
```
