### ISSUE TITLE
Allow external variables into markdown render

### ISSUE THREAD

**Issue by maximepvrt** [nuxt/content#2053]
I would like to request the addition of external variables support in Nuxt Content. As of now, it is not possible to use variables defined outside of the content file, which can limit the flexibility of the application.

In many cases, it is essential to have access to external variables to generate dynamic content or to implement complex logic. For instance, it could be useful to define site-wide variables or to read data from an external API.

Adding external variables support would greatly enhance the capabilities of Nuxt Content and make it a more powerful and flexible tool. It would also help developers to build more sophisticated applications while keeping the content organized and easy to manage.

It would be an extension of this feature https://github.com/nuxt/content/pull/1266

Thank you for considering my request.

**Comment by ManasMadrecha** [comment]
You can easily create 1 component, say "v.vue". 

And use it in your markdown file like this:

```html
:v{var="name"} <!-- `name` can be any global variable's key -->
```
Here, 

The `v` component
- Can use accept one `prop` called `var`. 
- Can fetch any global variable you have set up in your app, for e.g., via `appConfig`
- Use the prop as a key of the global variable
- And render it in the template

**Comment by maximepvrt** [comment]
I would like to inject a variable retrieved from `useFetch` into `<ContentSlot/>` using a props.

**Comment by maximepvrt** [comment]
@farnabaz What do you think ?

**Comment by ManasMadrecha** [comment]
In order to add random external variables into `data` so as to render it in markdown as a variable, you can **add the variables in the `afterParse` hook** of the Content Module. 

Refer this: https://content.nuxtjs.org/api/advanced#contentfileafterparse

Note: You can't add them after the markdown has already been rendered, by simply adding them as `prop` in the `template` section. 

So, in the `afterParse` hook, you can async fetch whatever you want, and then simply add it as a key of the `file`. The `afterParse` hook works as a custom `rehype`-plugin. While it will work, but if it doesn't work, then you can try adding them in a custom `remark`-plugin as well.

I had tried this in Content V1 as well to fetch GitHub releases and then add them as a key into the implicit frontmatter in the `afterParse` hook, to later render them in the markdown.

**Comment by maximepvrt** [comment]
@ManasMadrecha Thank you for your response and the helpful information. Just to clarify, does this mean that I need to fetch the external data within the `afterParse` hook itself ? Also, could you please provide an example that demonstrates how to implement this approach ? It would greatly assist me in understanding the process better. Thank you for your assistance.

**Comment by maximepvrt** [comment]
@ManasMadrecha 😉 Doc : https://content.nuxt.com/usage/markdown#example-2-define-in-external-with-contentrenderermarkdown

**Comment by ManasMadrecha** [comment]
Omg this is really cool @maximepvrt 👏🏻

**Comment by Rednas83** [comment]
Tried variables in markdown but I can't get it to work😭

**app.config.ts**
```
import { defineAppConfig } from "nuxt/app";

export default defineAppConfig({
  name: "playing with markdown",
  color: "red",
})
```

**markdown.md**
```
---
title: Markdown example
custom: Custom text
---

{{ title || 'Local variable like title work as expected' }}

{{ custom || 'Custom local variables are not supported' }}

{{ name || 'Global variables from app.config.ts are not working' }}

{{ app.config.name || 'Global variables from app.config.ts are not working' }}
```
**Returns**

<img width="339" height="141" alt="Image" src="https://github.com/user-attachments/assets/bcbfe06d-dde8-4a93-92e6-8e8737f302fd" />

Is it still suported? Preferable a solution with local variables so that it takes less memory and startup time🤞

Also tried [nuxt-mdx](https://github.com/acelletti/nuxt-mdx) but that has still has some issues as mentioned in https://github.com/acelletti/nuxt-mdx/issues/1

**Comment by maximepvrt** [comment]
https://content.nuxt.com/docs/files/markdown#binding-data ;-)

**Comment by ManasMadrecha** [comment]
@Rednas83 Prefix the variables with `$doc.`

**Comment by Rednas83** [comment]
Just tried it but that also only works for standard variables like `title` or `description`
```
---
title: 'Playing with markdown'
description: 'green'
customVariable: 'Custom Value'
---

{{ title || '❌title' }}

{{ $doc.title || '❌$doc.title' }}

{{ customVariable || '❌customVariable' }}

{{ $doc.customVariable || '❌$doc.customVariable' }}

::alert{:color=description}
 description
::

::alert{:color=$doc.description}
 $doc.description
::
```
**returns**
<img width="765" height="298" alt="Image" src="https://github.com/user-attachments/assets/41072a58-0c3b-4fe0-972e-967a1ae8706c" />

Can it be re-opened or should I create a new issue report?

**Comment by Rednas83** [comment]
Fixed it by validating the variables in **content.config.ts**🚀
```
import { defineContentConfig, defineCollection, z } from '@nuxt/content'

export default defineContentConfig({
  collections: {
    content: defineCollection({
      type: 'page',
      source: '**/*.md',
      schema: z.object({
        title: z.string(),
        description: z.string(),
        customVariable: z.string()
      }),
    })
  }
})
```

It doesn't seems to be required to prefix the variables with **$doc.**
```
---
title: 'Playing with markdown'
description: 'info'
customVariable: 'Custom Value'
---

{{ title || '❌title' }}

{{ customVariable || '❌customVariable' }}

::UAlert{:title=description :color="description"}
::
```
