### ISSUE TITLE
missing document for ProsePre

### ISSUE THREAD

**Issue by xarthurx** [nuxt/content#2276]
### Is your feature request related to a problem? Please describe

When trying to check the styles of code highlight, I saw a `ProsePre.vue` for the highlight section.
However, I cannot find any documentation on the website for this.
![image](https://github.com/nuxt/content/assets/1921878/bf13c242-adc6-416c-a706-0d5dd02ab3e6)

### Describe the solution you'd like
Add documentation of `ProsePre` for the Prose Component:
https://content.nuxtjs.org/api/components/prose

**Comment by xarthurx** [comment]
Additionally, as you can see in the image, the code highlight has a same background as the article, and is pretty hard to see.
Is `ProsePre` (seems to be a pre-processing component) the right place to go?

I don't find any documentation for the background customization of the code section either...

**Comment by nobkd** [comment]
What `<pre>` is: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre
> In short:
> - no whitespace collapsing
> - lines don't break if they are too long for the page
>
> This is very useful for code blocks to keep each line a line

The prose component source: https://github.com/nuxt-modules/mdc/blob/main/src/runtime/components/prose/ProsePre.vue

I'd say that the `<ProsePre>` is not listed there, because it does not have its own Markdown syntax.

But feel free to open a PR to add a description to the docs.

**Comment by ninedev-i** [comment]
I think you can close it now, it's [documented](https://content.nuxt.com/components/prose#prosepre)
