### ISSUE TITLE
External link syntax generates rel with comma separated values - is this expected?

### ISSUE THREAD

**Issue by ceigey** [nuxt/content#247]
Hi all,

I wasn't quite sure if this should be a bug report or not - at least for @nuxt/content.

I noticed when writing external links (e.g. `[Go to Wikipedia](https://en.wikipedia.org)`) that the tag generated looks like this:

```html
<a data-v-f58a9f50=""
  href="https://en.wikipedia.org"
  rel="nofollow,noopener,noreferrer"
  target="_blank"
>
  to wikipedia
</a>
```

In particular, the `rel` seems different to what I see recommended on MDN (which would be [to use space-separated keywords](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel)).

Is this intended behaviour, and if not, is this something for @nuxt/content to address, or is this a Remark (right lib?) issue upstream?

I'm noticing this so far with `npm run dev` on a Nuxt static export-style project.
Dependencies are:

* `"nuxt": "^2.13.0"`
* `"@nuxt/content": "^1.4.1"`

I have at least edited the markdown document via the dev-mode in-browser editing feature, if that has any relevance whatsoever.

I noticed [a similar issue on Gatsby](https://github.com/gatsbyjs/gatsby/issues/22719), which makes me think this is an upstream issue.

On a side note, thank you for your time on this great plugin.

**Comment by benjamincanac** [comment]
Hey @ceigey,

Thanks for reporting this issue. This is not related to `remark` because we get markdown as JSON AST.

For the `rel` we use [remark-external-links](https://github.com/remarkjs/remark-external-links) which adds `['nofollow', 'noopener', 'noreferrer']` to external links. The issue was in the `nuxt-content` component that converts the JSON AST to HTML.

#248 should solve this issue.
