### ISSUE TITLE
Syntax highlight breaks

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#2531]
### Environment

/

### Reproduction

check https://github.com/unjs/website as a reference.

This PR breaks syntax highlight https://github.com/unjs/website/pull/160

### Describe the bug

see title

**Comment by pi0** [comment]
I think latest deps should have not this issue anymore.

**Comment by trc-mathieu** [comment]
@pi0 
I think there are still some issues with highlighting. It doesn't seem to be working.
I took this example from the nuxt content website. (Maybe it's not highlighting in this case because of a wrong configuration of the code block -> `js [file.js]{4-6,7} meta-info=val` but there are only 3 lines.
<img width="816" alt="Screenshot 2024-05-30 at 11 30 28 AM" src="https://github.com/nuxt/content/assets/108015560/e234999d-9b67-4dfd-909b-82c8010aff7a">

You can notice that lines are not highlighted nor classes are added to the code block.

I also created a repro with the Nuxt documentation template, it does add classes but styling is missing. (I will push this repo a bit later)
I added this as the `nuxt.config.ts content entry`
```
content: {
    highlight: {
      // Theme used in all color schemes.

      // OR
      theme: {
        // Default theme (same as single string)
        default: 'github-light',
        // Theme used if `html.dark`
        dark: 'github-dark'
      }
    }
  }
  ```
  Here's the result of the code block, as you can see, the classes are added but css is missing.

<img width="1158" alt="Screenshot 2024-05-30 at 10 32 16 AM" src="https://github.com/nuxt/content/assets/108015560/a1694a46-e567-46a9-899f-38d281e19e59">

Any help would be appreciated on this.

**Comment by nandordudas** [comment]
@trc-mathieu some classes are missing, I'll make a new issue with proper reproduction. If you need a quick, temporary solution use styles below but __please wait for the fix from the authors__.

https://gist.github.com/nandordudas/a8487d89e212c9963b0433b3b073e027
