### ISSUE TITLE
Alternative to VuePress

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/content#260]
### Is your feature request related to a problem? Please describe.
I'm trying to generate a documentation website depending on the folder hierarchy somewhat like VuePress.
I have two main problem, first with Nuxt Routing not allowing me to view file in sub-folder and one with querying the API to generate a sidebar depending on the Markdown documents hierarchy.
Here's a codesandbox to follow along: https://codesandbox.io/s/nuxt-content-vuepress-alternative-ij4ip

### Describe the solution you'd like
Let's start with the the routing. I would like every file inside the `content` folder to have a route automatically generated for a specific path, somewhat like VuePress. For exemple, my `pages/documentation/_slug.vue` should be able to point to any of these files:
```
content/
    - README.md (work) // => `/documentation/`
    - test/ // => `/documentation/test`
        - README.md (does not work) // => `/documentation/test`
        - test.md (does not work) // => `/documentation/test/test`
```
As you can see from the sandbox, clicking on the links in the sidebar does not work and results in a 404 because I think Nuxt is trying to route to a `pages/` (vue file) instead of a `content/` (markdown file). It would be nice to be able to specify a path to generate sub-route for every root-folder of the `content/` folder, maybe ?
Also, the `README.md` or `index.*` should automatically be picked up to become the default route for each folder.

The second problem I have is with the API. It was partially corrected by Nuxt-content 1.4 by allowing to query nested folder and the `deep: true` config option, but I feel the API could be a little more like the Table of content one. For exemple, I would like to be able to query only to a `depth` of 2 or 3 to generate a manageable sidebar. Maybe an option to query page bellow the current on or from the root could be intresting too. For example, if I'm on `test/README.md` I could do ` await $content({ deep: true, depth: 2, fromRoot: false }).fetch();` and receive `test.md` and 2 level of children (if any). Also the result would need to be able to be grouped by `path`, although I could probably use `lodash` for this, but the critical path is that each route have a key that give their level just like headings in the TOC. This would allow use to style our sidebar in a similar manner to the TOC example: `:class="{ 'sidebar-depth--2': link.depth === 2, 'sidebar-depth--3': link.depth === 3 }"`

**Comment by mathe42** [comment]
Have a look at https://nuxtjs.org/guide/routing#unknown-dynamic-nested-routes this might help...

**Comment by azrikahar** [comment]
The reason why it's not working is because in your `pages/documentation/_slug.vue` file, the following line:

    const document = await $content(params.slug || "README", {
      deep: true
    }).fetch();

particularly `$content(params.slug || "README")` (disregarding the options.deep for now), it just means it is fetching the `/` directory of `content`, not nested ones like `content/XXX`. Hence why the "README" can map to `content/README.md`, but slugs like "test" will map to `content/test` **directory**, thus returning an array since you specified the options.deep config. This is evident when we try to go `https://ij4ip.sse.codesandbox.io/documentation/test`. It will work (as in not showing 404), but the reason we can't see anything is because now "document" is an Array, so this line `<nuxt-content :document="document"></nuxt-content>` in your `pages/documentation/_slug.vue` will not work properly when you pass in an Array instead of Object.

@mathe42 is spot on there. The dynamic nested routes are actually the crucial ingredient in this scenario. @mrleblanc101 can you kindly try the following steps for it to work in your case? (I have tested this myself, but I can try to upload this exact sample to a repo if you really want)

1. Move `pages/documentation/_slug.vue` file to `pages/documentation/_category/_slug.vue`.
2. For line 32-34 in the newly moved `_slug.vue` file, change it from

    ```js
    // old code
    const document = await $content(params.slug || "README", {
      deep: true
    }).fetch();
    ```

    into 

    ```js
    // new code
    const { category, slug } = params
    const document = await $content(category, slug || 'README').fetch()
    ```

3. Change the `:to` of NuxtLink in line 7, from

    ```js
    // old code
    <NuxtLink :to="link.path">{{ link.slug }}</NuxtLink>
    ```

    into

    ```js
    // new code
    <NuxtLink
         :to="
            link.slug === 'README'
            ? `/documentation${link.dir}`
            : `/documentation${link.path}`
        "
    >
        {{ link.slug }}
    </NuxtLink>
    ```

This 3rd step is to make it so README will use `dir`, which is `/` instead of `/README` in the URL. We have to append `/documentation` since your current ones doesn't have it. Perhaps it can be set as a publicRuntimeConfig ([Refer here](https://nuxtjs.org/guide/runtime-config/)) rather than hardcoding it.

Do let me know if it works for you :)

**Comment by mathe42** [comment]
You can just use in the pages folder a file `_.vue` which catches all routes. Then you can get the route with `route.params.pathMatch`.

**Comment by mrleblanc101** [comment]
Thanks @mathe42. I'll look into this. @azrikahar This wouldn't work as the folder depth is not fixed.

**Comment by azrikahar** [comment]
@mrleblanc101 No worries. I do understand the folder depth will not be fixed. Actually my intention was more towards clarifying how the nested routes work relative to the $content function which can accept multiple arguments, like so:

> You can also give multiple arguments: `$content('articles', params.slug)` will be translated to `/articles/${params.slug}`

_quote taken from [here](https://content.nuxtjs.org/fetching#contentpath-options)_

And the `/articles/${params.slug}` means grabbing content from `content -> articles -> files/dirs`, not to be mistaken with the actual URL/path in the browser.

**Comment by benjamincanac** [comment]
@mrleblanc101 Have you been able to find a solution to your issue? You can also take a look at the docs theme, it is built with an `_.vue` to achieve the behaviour you seek: https://github.com/nuxt/content/tree/dev/packages/theme-docs

**Comment by mrleblanc101** [comment]
Haven't had much time to play with this. This was a work side project and we're kinda overloaded now. Maybe soon, but I'll check this. Thanks !
