### ISSUE TITLE
there must be something wrong at skip() of queryCollections() in nuxt content 3， it doesnt work when i use it ，

### ISSUE THREAD

**Issue by shidaizaiweixiao** [nuxt/content#2867]
### Environment

npx nuxi info

### Version

v3

### Reproduction

i develop it at local

### Description

there must be something wrong at skip() of queryCollections() in nuxt content 3， it doesnt work when i use it ，

### Logs

```shell-script

```

**Comment by farnabaz** [comment]
Thanks for the issue, indeed there was an issue in the query builder. The issue is fixed in https://github.com/nuxt/content/commit/097cc7744be2c7c212f4c24aac07e4aaeaa6a1a3

The fix will be released in the next alpha but meanwhile, you can test using commit release `npm i https://pkg.pr.new/@nuxt/content@097cc77`

**Comment by zzdaddy** [comment]
same, maybe i should wait next next next  version ...

**Comment by farnabaz** [comment]
@zzdaddy Did you try with the commit release? `npm i https://pkg.pr.new/@nuxt/content@097cc77`

**Comment by zzdaddy** [comment]
> [@zzdaddy](https://github.com/zzdaddy) Did you try with the commit release? `npm i https://pkg.pr.new/@nuxt/content@097cc77`

not yet now😁 i'll try it. thanks!

**Comment by zzdaddy** [comment]
"@nuxt/content": "https://pkg.pr.new/@nuxt/content@097cc77"

👆it's worked
