### ISSUE TITLE
Not compatible with express serverMiddleware

### ISSUE THREAD

**Issue by danielroe** [nuxt/content#292]
> When a custom serverMiddleware is added that exports an express instance, all `@nuxt/content` client-side requests hang rather than resolving.

### Version
@nuxt/content: v1.4.1
nuxt: v2.13.3

### Reproduction link

https://codesandbox.io/s/nuxtcontent-demo-x11rc

### Steps to reproduce

1. Create serverMiddleware that exports an express instance that uses json middleware, for example:
   ```js
   import express from 'express'
   const app = express()
   // Note that without following line this bug is not reproduced
   app.use(express.json())
   app.get('/api/test', (req, res) => res.end())
   export default app
   ```
2. Add it to `nuxt.config.js`:
   ```js
   serverMiddleware: [require.resolve("./api/test.js")],
   ```

### What is expected?

I expect adding additional endpoints as above should not interfere with the endpoint `@nuxt/content` adds.

### What is actually happening?

All `@nuxt/content` client-side requests hang rather than resolving.

**Comment by mawangod** [comment]
same bug

**Comment by danielroe** [comment]
I have just refreshed the reproduction accessible above https://codesandbox.io/s/nuxtcontent-demo-x11rc - it is still giving the same issue.

Below is a video of the behaviour:
![Screen Recording 2020-11-05 at 11 23 57](https://user-images.githubusercontent.com/28706372/98235643-023cf880-1f5a-11eb-8854-223ff797cd76.gif)

**Comment by Atinux** [comment]
My bad, I thought the serverMiddleware was not working, I see the issue now. Will investigate.

**Comment by NozomuIkuta** [comment]
@Atinux @danielroe 

I've looked into this issue to have a fun on weekend. 

If I understand it correctly, the root cause is that `express.json()` (i.e. [body-parser](https://github.com/expressjs/body-parser) package, or [raw-body](https://github.com/stream-utils/raw-body) package more accurately) consumes all the stream before the `req` is passed to Nuxt Content's middleware.

So, the event listeners below are never called, and consequently the promise remains pending forever:

https://github.com/nuxt/content/blob/ebaedede5935f597fe325322ef57f09f6222e1ff/packages/content/lib/middleware.js#L19-L28

This promise stuck can be avoided by adding a condition to if-block, because body-parser sets `req._body` as `true` when it populates `req.body`:

```javascript
if (['POST', 'PUT'].includes(req.method) && !req._body) { /* ... */ }
```

But, this solution would not be appropriate because now Nuxt Content becomes wary about behavior of package(s) that it doesn't depend on. Perhaps, do you think it's fine only if we provide some guide in documentation?

By the way, there might be more information that I have not yet found, but I would stopped research here since it's over 1:30 a.m. in Japan. I think I should go to bed for health, rather than sticking to have a fun. 🛏️ 🙏 🤣

**Comment by NozomuIkuta** [comment]
@Atinux @danielroe 

Searching Node.js documentation, I found that `req`, which is of `http.IncomingMessage` class,  has `readableEnded` property inherited from `stream.Readable` class.

`readableEnded` property  becomes `true` when `'end'` event is emitted ([link](https://nodejs.org/api/stream.html#stream_readable_readableended)).

So, the following condition would be enough.

```javascript
if (['POST', 'PUT'].includes(req.method) && !req.readableEnded) { /* ... */ }
```

Just in case, this property is matured enough because this was added in v12.9.0 (note: v14 is current LTS).

I will submit a PR after sending this message, so please double-check whether this approach is reasonable. 🙋‍♀️

**Comment by NozomuIkuta** [comment]
Oh, wait. 

I've remembered that it's officially said in docs that Nuxt's `servierMiddleware` is  an [connect](https://github.com/senchalabs/connect) app.

Then, is it OK to simply check [body-parser](https://www.npmjs.com/package/body-parser)'s `req._body` flag?
Actually, [body-parser](https://www.npmjs.com/package/body-parser) is an official package by Connect/Express team.

**Comment by NozomuIkuta** [comment]
Sorry to post message in a row.
But if we can't assume the consumer of the stream is body-parser, we can't determine which property is populated without a cue.

If it's body-parser, we can use `req.body` simply, but if someone uses other middleware which modifies other part of `req`, Nuxt Content can't find it.

Compromise would be to let users to set the property name as Nuxt Content' option, although it looks not elegant. 😕

**Comment by NozomuIkuta** [comment]
@Atinux 

Since "done is better than perfect", I submitted a PR where Nuxt Content gets request body by which an option, whose value is `'body'` (i.e. `req.body`), assuming body-parser is already used in the pipeline.

User can override this option so that Nuxt Content can be agnostic on what server middleware consumes read stream and which property is populated.

Please see the PR for more detail.
