### ISSUE TITLE
[v3] `resolveComponent` stopped working when the name of a global component is passed to `is` prop

### ISSUE THREAD

**Issue by BayBreezy** [nuxt/content#2930]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.18.1`
- Nuxt Version:     `3.15.0`
- CLI Version:      `3.17.2`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@10.8.2`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@vueuse/nuxt@12.2.0`, `@nuxtjs/tailwindcss@6.12.2`, `radix-vue/nuxt`, `@samk-dev/nuxt-vcalendar@1.0.4`, `@vee-validate/nuxt@4.15.0`, `@nuxt/content@3.0.0-alpha.8`, `@nuxtjs/color-mode@3.5.2`, `@morev/vue-transitions/nuxt@3.0.5`, `@nuxt/eslint@0.7.4`, `nuxt-swiper@2.0.0`, `v-wave/nuxt`, `@nuxt/image@1.8.1`, `@nuxt/icon@1.10.3`, `@nuxt/fonts@0.10.3`, `@nuxtjs/seo@2.0.2`, `@vite-pwa/nuxt@0.10.6`
- Build Modules:    `-`

### Reproduction

Not available

### Describe the bug

After upgrading to content v3, this syntax no longer works

```html
 <component is="globalComponentName"  />
```

### Additional context

In v2, this worked with mo issues. It stopped working after updating to content v3

### Logs

```Shell

```

**Comment by BayBreezy** [comment]
For those who find this and want to add functionality for global components like in v2, here you go

- Add these to the top of the `nuxt.config` file

```ts
import { createResolver } from '@nuxt/kit'

const { resolve } = createResolver(import.meta.url)
```

- Add this to `modules` array

```ts
(_, nuxt) => {
      nuxt.hook('components:dirs', (dirs) => {
        dirs.unshift({ path: resolve(PATH_TO_GLOBAL_CONTENT_FOLDER), pathPrefix: false, prefix: '', global: true })
      })
    }
```

Be sure to replace `PATH_TO_GLOBAL_CONTENT_FOLDER` with the path: E.g: `./app/components/content`

**Comment by farnabaz** [comment]
Content v3 does not register components as global. If you want to mark components global, you can either change them to global (like your own solution) or mark an individual component using `.global.vue` suffix.

**Comment by BayBreezy** [comment]
That is ok @farnabaz I was under the impression that Nuxt itself marked everything in the `content` folder as global.
I never knew that it was being done by the module instead. So that is where the confusion was.

**Comment by takayumi** [comment]
> * Add this to `modules` array
> 
> (_, nuxt) => {
>       nuxt.hook('components:dirs', (dirs) => {
>         dirs.unshift({ path: resolve(PATH_TO_GLOBAL_CONTENT_FOLDER), pathPrefix: false, prefix: '', global: true })
>       })
>     }
> Be sure to replace `PATH_TO_GLOBAL_CONTENT_FOLDER` with the path: E.g: `./app/components/content`

This solved my problem. Thank you @BayBreezy! I’m new to Nuxt Content and noticed that without this explicit global registration, my components inside components/content weren’t available in the visual editor or preview unless I first used them directly in a content file BEFORE using them in Nuxt Studio.

It seems that in Nuxt Content v3, unlike v2, the source code adds the components folder without the `global: true` flag, which prevents automatic global registration. The official docs don’t mention this, so it caused some confusion for me.

It seems your migration code didn't make it to the [newer docs](https://content.nuxt.com/docs/studio/content#vue-components).

It does, however, show how to [mark Nuxt UI components as global](https://content.nuxt.com/docs/studio/content#integrate-built-in-components-from-external-libraries) since it's an "external library". I was under the impression that I didn't need to since the components were in my project *locally*.

Maybe the docs need an update again?

**Comment by BayBreezy** [comment]
Happy I could help :) 
I wanted this bit to be added to the migration section of the docs, but it's OK. Hopefully others come here and see it too
