### ISSUE TITLE
Possibility to have a views count on static nuxt without backend

### ISSUE THREAD

**Issue by ghazimuharam** [nuxt/content#393]
is it possible to have a dynamic views page count without having a backend?

**Comment by cogor** [comment]
AWS Lambda function + dynamoDB for storing post views

**Comment by davydnorris** [comment]
... and Cloud Functions + Cloudant in the IBM Cloud side, or Firebase.

The one thing I have done before is used IBM Cloud Functions to hook to a Github repo, then you basically get it to push a commit. If you served your static pages from your GitHub that would work

**Comment by ghazimuharam** [comment]
> AWS Lambda function + dynamoDB for storing post views

How do you deal with the unique ID?

**Comment by ghazimuharam** [comment]
> ... and Cloud Functions + Cloudant in the IBM Cloud side, or Firebase.
> 
> The one thing I have done before is used IBM Cloud Functions to hook to a Github repo, then you basically get it to push a commit. If you served your static pages from your GitHub that would work

So I need to add views in frontmatter, and push a commit everytime someone visit the content?

**Comment by davydnorris** [comment]
> So I need to add views in frontmatter, and push a commit everytime someone visit the content?

No, if I was doing it that way I would save a JSON file with all the ids(slugs) and views - don't update your main files. If you were looking at something that was being updated less often, like comments, you could use [Staticman](https://staticman.net/).

However if you're expecting a reasonable level of views you'd be much better off with a db back end of some sort, and I would use a relational db, not a NoSQL db, or MongoDB if you have to use NoSQL because updates to records in NoSQL are expensive.

I would have an increment routine that updates the individual page records but a fetch routine that pulls all the page counts at once in a single call

**Comment by ghazimuharam** [comment]
> 
> > So I need to add views in frontmatter, and push a commit everytime someone visit the content?
> 
> No, if I was doing it that way I would save a JSON file with all the ids(slugs) and views - don't update your main files. If you were looking at something that was being updated less often, like comments, you could use [Staticman](https://staticman.net/).
> 
> However if you're expecting a reasonable level of views you'd be much better off with a db back end of some sort, and I would use a relational db, not a NoSQL db, or MongoDB if you have to use NoSQL because updates to records in NoSQL are expensive.
> 
> I would have an increment routine that updates the individual page records but a fetch routine that pulls all the page counts at once in a single call
> 

Thanks,I think using JSON files is quite reasonable since it's just needed for views count for a small blog.
