### ISSUE TITLE
Add defaultDocsDir to settings

### ISSUE THREAD

**Issue by kaka-ruto** [nuxt/content#430]
### Is your feature request related to a problem? Please describe.
Currently, the `Edit this page on Github` links to a dead page because the Github link is hardcoded to the `docs/content` directory.

When you create a new project with `npm init nuxt-content-docs <project-name>`, you don't get the `docs` directory by default, but the `content` directory only.

### Describe the solution you'd like
1. `nuxt-content-docs` should create a new directory, `docs`, and place the `content` directory inside it
2. Add a `defaultDocsDir` to `content/settings`, letting it default to the full path of the `content` folder, and if set, points to `{<user_folder>/content}`

### Describe alternatives you've considered
Manually creating the docs folder and placing the content folder inside it.

### Additional context
https://github.com/nuxt/content/blob/138f67ccb002a8f52bdb081aac2764f61c8d72f9/packages/theme-docs/src/components/global/app/AppGithubLink.vue#L35

**Comment by LloydTao** [comment]
Yeah, I'm looking for this. It's humorous that the default project name is `project` but throws a dead link for anything except `docs` 😼 

Option 2 is much better for backwards compatibility.

**Comment by LloydTao** [comment]
## Provisional Fix
I may find some time to implement this tomorrow 😁 
### Step 1
Replace `docs` with `${this.settings.name}`:
https://github.com/nuxt/content/blob/138f67ccb002a8f52bdb081aac2764f61c8d72f9/packages/theme-docs/src/components/global/app/AppGithubLink.vue#L35 
### Step 2
Add a placeholder for `name`, similar to `title`:
https://github.com/nuxt/content/blob/157262cc932b9644c5c0747ea79a361ededb60a5/packages/create-nuxt-content-docs/template/content/settings.json#L2
### Why?
We know that it's `name`, because that's the field taken by the CLI:
https://github.com/nuxt/content/blob/138f67ccb002a8f52bdb081aac2764f61c8d72f9/packages/create-nuxt-content-docs/src/saofile.js#L5

**Comment by benjamincanac** [comment]
Indeed, we assumed for now that people would use a `docs/` directory, this needs improvements. A PR is more than welcome 🙂

**Comment by kaka-ruto** [comment]
@LloydTao your provisional fix seems awesome. So `name` is the project directory folder? Or users will have to create a new folder inside the project dir and assign it's 'name' to the `name` variable in settings?

**Comment by LloydTao** [comment]
> @LloydTao your provisional fix seems awesome. So `name` is the project directory folder? Or users will have to create a new folder inside the project dir and assign it's 'name' to the `name` variable in settings?

yeah, the `name` parameter taken at the CLI is the project directory folder, so passing it to the `settings.json` should be trivial unless there's some third part i haven't discovered yet

**Comment by LloydTao** [comment]
> okay, am i going crazy? i generated a project last night and it made a root folder, but made one just now to test and there's no root 😣 if it's really not generating inside a root directory, then why's it asking for one? 

---
### edit:
turns out i'm not an idiot. 

- throwing an argument (i.e. `create-nuxt-content-docs <project>`) will use the argument as the root directory. 
- using no argument is effectively the same as `create-nuxt-content-docs .`

in the second case, it seems like it's pointlessly asking for a project name, and doesn't use it anywhere.

**this is the same behaviour as `npx create-nuxt-app`**:

![image](https://user-images.githubusercontent.com/41923457/91770390-01de5500-ebd9-11ea-842c-0dab5a42ba5c.png)

### what does this mean?

the `name` field taken in the CLI won't actually match the directory if `create-nuxt-content-docs` doesn't take an argument

### what can we do?

where an argument is passed for `create-nuxt-content-docs`, my previously mentioned fix is fine 😁 

however, where **no argument** is passed, i propose that the project name is not prompted for, and instead takes the root directory as the value for `name`. 

we'd also want to reflect this change in https://github.com/nuxt/create-nuxt-app/

### good idea?

i'd love your opinion on this @benjamincanac:

1. when `npx create-nuxt-app` or `npx create-nuxt-content-docs` is called without an argument, do not prompt for the project name, and use the current directory for `name` instead

**Comment by kaka-ruto** [comment]
Just my two cents, I think it's ok to prompt for the project name still, just to confirm that that is actually what you want your name to be? Whether the current directory or one you provided as an argument, then at that point you can either skip or enter another name

**Comment by benjamincanac** [comment]
@kaka-ruto @LloydTao The `defaultDir` option has been implemented in the linked PR.

However, I don't plan to make any change to the `create-nuxt-content-docs` CLI for now, it follows the same logic as `create-nuxt-app` on purpose.
