### ISSUE TITLE
Cannot translate the value of keypath 'search.placeholder' for new Nepali Language

### ISSUE THREAD

**Issue by 47BulletProof** [nuxt/content#431]
### Version
@nuxt/content: 1.7.0
nuxt: 2.14.3
@content-theme-docs:  0.5.2

### Steps to reproduce
When new language is added:

```
export default theme({
    i18n: {
        locales: () => [{

            code: 'ne',
            iso: 'ne-NE',
            file: '~/locales/ne-NE.js',
            name: 'Nepali'
        }, {
            code: 'en',
            iso: 'en-US',
            file: 'en-US.js',
            name: 'English'
        }],
        defaultLocale: 'ne'
    },
})

```

### What is Expected?
Language Translation file not found

### What is actually happening?
English is working fine but for another language, the language file is not loading.
Is there a way to load the file.

I am getting the following error:

` WARN  [vue-i18n] Cannot translate the value of keypath 'search.placeholder'. Use the value of keypath as default.                                                                                                            16:22:25`

**Comment by azrikahar** [comment]
This is because the files are located over here: https://github.com/nuxt/content/tree/dev/packages/theme-docs/src/i18n, so you will need to make a PR to create a ne-NP.js file over there :)

With that said, since you will need to wait until your PR is merged for this to work, let me propose a working alternative at the mean time.

## Adding a new language

Change the `nuxt.config.js` file content into this:

```js
export default theme({
    i18n: {
        locales: [{
            code: 'ne',
            iso: 'ne_NP',
            // file: 'ne_NP.js',
            name: 'Nepali'
        }],
        defaultLocale: 'ne',
        vueI18n: {
            formatFallbackMessages: true,
            messages: {
                ne: {
                    search: {
                        placeholder: 'NE Search the docs (Press "/" to focus)'
                    },
                    toc: {
                        title: 'NE On this page'
                    },
                    article: {
                        github: 'NE Edit this page on GitHub'
                    }
                }
            }
        }
    },
})
```

You'll just need to translate the `search.placeholder`, `toc.title`, and `article.github` sentences to Nepali language. Notice that I've commented out the line `file: 'ne_NP.js' for the mean time just so we know this line does nothing now. You can uncomment this and remove the whole `vueI18n` option once your PR is merged. I have tested this myself and it works like a charm.

@benjamincanac would this approach of adding new language be appropriate to be documented? Or perhaps there are plans for other ways of doing this? Sorry for the cc since I'm not sure to ping who from the team for this sort of inquiry.

---

Btw I believe the iso code for Nepali language is `ne-NP`, as seen over these links:

- https://support.mozilla.org/ne-NP/kb/dashboard/metrics/ne-NP?category=&product=focus-firefox
- https://www.localeplanet.com/dotnet/ne-NP/index.html

**Comment by 47BulletProof** [comment]
@azrikahar  Thanks. I tried your method and it's working. But I think there must be a better way to write in some other translation file as the work gets bigger.
I have also added the file here https://github.com/nuxt/content/tree/dev/packages/theme-docs/src/i18n as you have suggested.
Let's wait for the core team to work out on this one.
Thanks again!

**Comment by azrikahar** [comment]
>  Thanks. I tried your method and it's working. But I think there must be a better way to write in some other translation file as the work gets bigger.

Glad it works. You're welcome :) yea the problem now is the `file` option is referring to the directory inside the `@nuxtjs/content-theme-docs`, but it can be misleading for developers without knowing it.  So I did also initially had the same confusion as you had. Perhaps there should be a warning or info about this in the official docs. 

One way I think that is slightlyyyyy better as it gets bigger is to separate out the messages and import it instead, like so:

### nuxt.config.js

```js
import theme from '@nuxt/content-theme-docs'
import messages from './locales/messages'

export default theme({
    i18n: {
        locales: [{
            code: 'ne',
            iso: 'ne_NP',
            name: 'Nepali'
        }],
        defaultLocale: 'ne',
        vueI18n: {
            formatFallbackMessages: true,
            messages
        }
    },
})
```

### /locales/messages.js

```js
export default {
    ne: {
        search: {
            placeholder: 'अभिलेख खोज्नुहोस (ध्यान केन्द्रित गर्न "/" थिच्नुहोस)'
        },
        toc: {
            title: 'यस पृष्ठमा'
        },
        article: {
            github: 'यस पृष्ठलाई GitHub मा सम्पादन गर्नुहोस'
        }
    }
}
```

> I have also added the file here https://github.com/nuxt/content/tree/dev/packages/theme-docs/src/i18n as you have suggested.
Let's wait for the core team to work out on this one.

Thanks for making the PR. Yup I'm sure it'll be more intuitive since this theme is just released within this month. Cheers

**Comment by 47BulletProof** [comment]
@azrikahar Yes, importing will also be a good idea. I will implement that one too.
PR is also merged.
Thanks.
