### ISSUE TITLE
Cannot filter posts by date range

### ISSUE THREAD

**Issue by davydnorris** [nuxt/content#441]
## Version
@nuxt/content: 1.7.1
nuxt: 2.14.4

### Reproduction Link
https://codesandbox.io/s/happy-jepsen-1x3mo?file=/pages/blog/index.vue

### Steps to reproduce
Create a fetch for content and apply a where filter using dates - none of the following work:

```js
const startDate = new Date(this.dateFilter.setDate(1));
const endDate = new Date(this.dateFilter.setMonth(this.dateFilter.getMonth() + 1, 1));

postQuery = postQuery.where({ createdAt: { $between: [startDate, endDate] } });
postQuery = postQuery.where({ createdAt: { $between: [startDate.toISOString(), endDate.toISOString()] } });

postQuery = postQuery.where({
  $and: [
    { createdAt: { $gte: startDate } },
    { createdAt: { $lte: endDate } }
  ]
});

postQuery = postQuery.where({
  $and: [
    { createdAt: { $gte: startDate.toISOString() } },
    { createdAt: { $lte: endDate.toISOString() } }
  ]
});

// In addition, custom filter functions are completely ignored - this has no effect. No console output and all records returned:
postQuery = postQuery.where((obj) => { console.log('obj=', obj); return false; });
```
### What is Expected?
a correctly filtered set of records are returned

### What is actually happening?
no records are returned at all, or in the case of the customer filter, the filter is not being called

**Comment by azrikahar** [comment]
I believe we were able to solve this over at #437, particularly these 2 comments:

- https://github.com/nuxt/content/issues/437#issuecomment-684638126
- https://github.com/nuxt/content/issues/437#issuecomment-684652420

Though with that said, this feels like an instance of gotcha particularly the date being passed into the `where` query. It will only work properly if we use `new Date(date).valueOf()` instead of just `new Date(date)`.

Another reason that sort of convinced me `new Date(date)` is enough/correct is because this pattern is used in the [**Example** code section in the **Fetching content** page of the official docs](https://content.nuxtjs.org/fetching#example), so I'm not sure what would be the consensus here in terms of documenting this date interaction.

**Comment by davydnorris** [comment]
Yes - agree. I feel this is more a work around than a fix, but it got me working at least
