### ISSUE TITLE
Build does not fail on error

### ISSUE THREAD

**Issue by nielsdB97** [nuxt/content#456]
### Version
@nuxt/content: 1.8.1
nuxt: 2.14.3

### Reproduction Link

https://codesandbox.io/s/nuxt-content-fail-build-on-error-fv7w1?file=/pages/page-with-error.vue

### Steps to reproduce
1. Open [codesandbox](https://codesandbox.io/s/nuxt-content-fail-build-on-error-fv7w1?file=/pages/page-with-error.vue)
2. Open a new terminal tab
3. Run `yarn generate --fail-on-error`
4. See an error being logged in the build output
5. See exit code 0 with message `Done in X.XXs.`

### What is Expected?
The build will fail when an error is thrown when the `--fail-on-error` flag is passed by exiting with an error code greater than 0.

### What is actually happening?
The build does not fail. It instead only shows the errors and exits like the build was successful.

**Comment by azrikahar** [comment]
Hi @nielsdB97. It seems like this was fixed in [Nuxt 2.14.4](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.4) by [this PR](https://github.com/nuxt/nuxt.js/pull/7948). I have also tried your codesandbox with the latest version of Nuxt and it fail properly now. Here are some screenshots:

### Confirming Nuxt 2.14.5 is used in the sandbox

![chrome_iugh9ZsIG3](https://user-images.githubusercontent.com/42867097/93001536-487d6900-f562-11ea-8b0f-2fe3b4674c37.png)

### The resulting build fail error output

![chrome_m5sWiClcVr](https://user-images.githubusercontent.com/42867097/93001541-516e3a80-f562-11ea-9813-8aa54865f2e7.png)

**Comment by nielsdB97** [comment]
@azrikahar hey Azri, thanks for your response!

You're right, the issue in the codesandbox indeed appears to be fixed with the new release.
Apparently the issue I'm having even goes a step further than expected.

To be sure I updated the codesandbox with some code that represents my usecase. I'm using Nuxt Content to 'fetch' content from JSON/Markdown files. To do this consistently I have a helper function which calls the fetch function and throws an error if the returned content is undefined.
If an error occurs during the content retrieval the build still does not fail.

However, this seems to be related to 'static' exporting. When you switch the new `ssr` option in `nuxt.config.js` to `true`, it fails as expected. However when it is set to `false` (like in the project I'm working on) it does not fail.

It appears that this exact issue is being tracked in #7742. If that is correct feel free to close this issue 😄 
Thanks again!
