### ISSUE TITLE
Markdown data is not reactive

### ISSUE THREAD

**Issue by 1cepeak** [nuxt/content#519]
I'm trying to bind some data into v-model of my custom checkbox component and, when i'm trying to change v-model via clicking on checkbox, data does not updating.

### Version
@nuxt/content: v1.8.1
@nuxt/content-theme-docs: ex: v0.6.1
nuxt: v2.14.5

### Reproduction Link
https://codesandbox.io/s/nuxt-content-reactivity-issue-ev003

**Comment by AlexanderBelokon** [comment]
It seems to me that [Vue.js docs](https://vuejs.org/v2/api/#functional) imply that functional components don't support reactivity:
> `functional`
> Causes a component to be stateless (no data) and instanceless (no this context). They are only a render function that returns virtual nodes making them much cheaper to render.

I'll try to look at the source to confirm this, but I'm afraid it might not be `nuxt/content` bug, but rather a `vue.js` feature

**Comment by AlexanderBelokon** [comment]
It turns out that our document is reactive already and all we needed was correct scope in eval. I've written a proof-of-concept that works and will make a PR out of it tomorrow

**Comment by AlexanderBelokon** [comment]
My PR solves this issue, but there are a couple of serious caveats:
1. [Customizing component `v-model`](https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model) doesn't work, since we don't fetch components' definitions to dig around in their properties. It's probably doable, but I'm not sure it's worth it at this point.
2. [Native inputs](https://vuejs.org/v2/guide/forms.html) have _a lot_ of [custom logic](https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/directives/model.js). I've implemented most of them for our use on a new branch, but it's a couple of dozens of lines of code, and there is still a serious bug there:
3. Native inputs lose reactive updates as soon as user changes their value. They continue to update the model on `change`/`input`, but stop receiving any updates themselves. I'm not really sure why that is as of yet, and it might be fixable if I get a reference to the rendered input element on an event and somehow update its value myself, but that will add even more complexity.

So my question is: do you think I should continue down this path?

**Comment by codenomnom** [comment]
@AlexanderBelokon I'm in so much need of that feature right now! 😄 I do believe even with the abovementioned caveats, your support for reactivity is a huge improvement!

Correct me if I'm wrong, but a lot of people would use it the same way I need it: I have a lot of pages/content, and I want to use a simple store to provide `Hello, Alexander` to some places. Those are a few simple placeholders that would change upon user interaction (unfortunately I cannot load that data upfront and populate it, it's user input controlled). And that's all - updates based on simple user interaction handled elsewhere - I don't believe anyone expects to have a full blown reactivity anyway.

I'd be more than happy to see your PR merged as it is right now 😛 Or at least some statement if that's to be expected or not implementing it whatsoever. Thank you for the great work, have a great year!
