### ISSUE TITLE
Implement createdAt and UpdateAt in Docs Theme

### ISSUE THREAD

**Issue by b1rdhous3** [nuxt/content#535]
### Describe the solution you'd like
It would be helpfull if you could see the values of createdAt and updatedAt at every page in the docs. Maybe it would be even more helpfull to see the updatedAt value since a User could see at first glance if something ist new. 
Since these informations are available at every page we could show them. 

AFAIK there is no build in function at the moment. 

I have wirtten a small component which would display it in the prev next page area. It was experimental. Before I continue I would like to hear your opinion on this. 

### Describe alternatives you've considered
Maybe beforeRender

**Comment by NozomuIkuta** [comment]
I agree with your idea! 👍 
It is helpful to show how old the information is.

For us to be able to continue discussion, being on the same page, I've modified a part of HTML via chrome dev-tools.
Does it looks like what you have been thinking?

<img width="740" alt="Screen Shot 2020-10-25 at 18 26 53" src="https://user-images.githubusercontent.com/16436160/97104024-c2714800-16f3-11eb-91f6-6028e2690957.png">

In addition, I briefly took a look at [the corresponding part of source code](https://github.com/nuxt/content/blob/162d54b8074b4777434f213e90ddc47300b6b27a/packages/theme-docs/src/pages/_.vue#L25), and found that we can achieve the goal by modifying `AppGitHubLink` component (renaming may be  needed, though).

If I understand it correctly, `updatedAt` property is available on `document` object so it seems not so complicated to implement.

One thing to consider is internationalization, since formats of date differ from one country to another (the sample above is based on Japanese format).

**Comment by NozomuIkuta** [comment]
Even if this feature is not accepted by authors, we will be able to achieve the goal by overriding the default components, which become available when #542 is released.

**Comment by Geminii** [comment]
> Actually I do like the idea of adding it (but not in italic), PR welcome 😀

I will to purpose a PR for this (in my todo list), really nice idea 😀
