### ISSUE TITLE
ERROR operatorPackage[operator] is not a function       

### ISSUE THREAD

**Issue by sandoche** [nuxt/content#581]
### Version
@nuxt/content: v1.9.0
nuxt: v2.14.7

### Reproduction Link
https://github.com/sandoche/CuratedStack-nocode-template/tree/issue-nuxt-content

### Steps to reproduce
1. Clone https://github.com/sandoche/CuratedStack-nocode-template
2. Go to branch `issue-nuxt-content`
3. Run `npm run dev`
4. Click on 'Open source' or 'Productivity'

### What is Expected?
To load the content.

### What is actually happening?
```
 ERROR  operatorPackage[operator] is not a function                                                           18:37:38

  at result_set_ResultSet.find (node_modules\@lokidb\loki\lokidb.loki.js:1418:50)
  at QueryBuilder.where (node_modules\@nuxt\content\lib\query-builder.js:73:29)
  at node_modules\@nuxt\content\lib\middleware.js:107:19
```

Note that when you open the page in a new tab it does work.
But when you click direcly it does not and give this error.

**Comment by neelansh15** [comment]
I'm having the same issue. Loading the page in new tab works but somehow nuxt-link doesn't work.
I have two Content API calls. It is the second one which causes this. I don't know if this is an issue with nuxt-link or the Content API

**Comment by neelansh15** [comment]
> I'm having the same issue. Loading the page in new tab works but somehow nuxt-link doesn't work.
> I have two Content API calls. It is the second one which causes this. I don't know if this is an issue with nuxt-link or the Content API

I resolved this by querying all the posts in my content/posts folder and then using the javascript `.filter()` function to filter the posts I want. Turns out, the error is in the `where` clause. 
I hope this bug gets resolved because querying for all the posts on each page load is not a good idea.

**Comment by sandoche** [comment]
I ended up do it like you said and removed nuxt content, I had another issue, changing the content didn't update the page.

**Comment by AlexanderBelokon** [comment]
I've reproduced your issue and the problem is in your property name `categories_slugs`. Underscore has special meaning in `nuxt/content`'s `.where()` and it misunderstands your intention. If you rename `categories_slugs` to anything without underscores, the problem goes away.

**Comment by ldrummond** [comment]
Is this still an issue? Are you basically not able to use underscore characters in keys? Some CMS systems by default use underscore separated (snake case) keys for fields. If you can't use `.where()` to parse values with an underscore, that seems like a bug or worth mentioning in the docs.

**Comment by lcherone** [comment]
Should be mentioned in docs, with one of the nice yellow alerts :)

**Comment by johnnycube** [comment]
Even though the warning does help - it is unfortunate since in my case I am not able to alter the content source files. I have to work with .json files which contain e.g. "start_date" as a field.

Any way how I can escape the text or handle it gracefully without touching the source files beforehand?

**Comment by NozomuIkuta** [comment]
@johnnycube 

You can modify properties of _documents_ before they are inserted to DB on `content:file:beforeInsert` hook ([link](https://content.nuxtjs.org/advanced#contentfilebeforeinsert)).

**Comment by Segundo-hub** [comment]
`.where({ type: { $eq: tags || 'culture' } })`


That solved the problem for me, as it turns out that in the first craga it is receiving undefined. Let's see if it lasts a long time, although I already passed the tests

**Comment by 0x199x** [comment]
Still an issue. This should probably be fixed.. the application shouldn't crash due to an undefined value in a where clause, the offending post should just be excluded from the result set.  

I've run into this a few times now and I always forget the solution and end up back at this post.  

One annoying side effect of this issue is that you have to have all of your markdown files structured exactly the same.  I wanted to add `stickied: true` to a handful of posts, to keep them pinned at the top of the list, and I ended up having to set `stickied: false` to every other post to work around this because they came back undefined and crashed the site.  

unfortunately `$contains: something || undefined || null`  doesn't work
