### ISSUE TITLE
Loading sub-directory content as categories

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/content#641]
Hi, I'm trying to write help articles based on a series of folders and content files within them, for example:

```
content/
├─ help/
│  ├─ account/
│  │  ├─ introduction.md
│  │  ├─ all-about-accounts.md
│  ├─ domains/
│  │  ├─ introduction.md
│  │  ├─ all-about-domains.md
│  ├─ monitors/
│  │  ├─ introduction.md
│  │  ├─ all-about-monitors.md
```

My sub-folders are my categories, and each `introduction.md` file is it's meta details which can then be displayed on some blog page showing all the categories. All the other files in those folders are the individual posts.

I want my URLs for instance to be: `/help/account/all-about-introduction` but I'm having trouble displaying and obtaining the content for each of those using the `fetch()` method.

I've got a page and folder set up like this:

```
pages/
├─ help/
│  ├─ index.vue
│  ├─ _slug/
│  │  ├─ _slug.vue
```

And my async function to try and get data from my category folders within `/_slug/_slug.vue` is:

```javascript
async asyncData ({ $content, params }) {
  const guide = await $content('help/account', params.slug)
                      .fetch()

  return {
    guide
  }
}
```

How can I achieve this?

**Comment by NozomuIkuta** [comment]
@sts-ryan-holton 

You need to fix 2 parts.

One point is that URL params must be unique in a path, since `params` object is a map of param name and its value.
Since you defined `_slug` 2 times, one for category is overwritten by the other for namely slug.

Let's rename first `_slug` as `_category`.

The other point is that first argument of `$content()` must be dynamically set according to `params`.
Otherwise, you always fetch a certain document in the static path.

[Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) are definitely for such use case.

```javascript
async asyncData ({ $content, params }) {
  const { category, slug } = prams
  const guide = await $content(`${category}/${slug}').fetch()

  return {
    guide
  }
}
```

[Demo (CodeSandbox)](https://codesandbox.io/s/serverless-leaf-lw4kp?file=/pages/_category/_slug.vue)

---

Thing to consider

First, if you access `http://domain.com/category/` in the demo, you will see error page. This is because there is no corresponding file in `content` directory (e.g. `category-1/`). You have to define a kind of redirect logic.

Second, you use same file name more than one time. Since filename is used as `slug` property of document, the documents are un-unique in Nuxt Content database in terms of `slug` property. You may have in trouble when you want to fetch prev/next page of current page, with  [`sortBy()` query function](https://content.nuxtjs.org/fetching#sortbykey-direction) and [`surround()` query function](https://content.nuxtjs.org/fetching#surroundslug-options). This is because `surround()` query function lets database return the first-match document in the sorted array of documents.

As a result, if you try to show prev/next links of current page, they may be wrong.

---

@Atinux 

Sorry to bother you. 🙇 

But, as far as I know, there is no explanation in docs that slugs are supposed to be unique in `content` directory, for `fetch()` to work as we expect.

Is it kind of common sense in web industry that slug is always unique?
Actually, I think it is natural that multiple category has same slug, like @sts-ryan-holton does.

Fetching documents, always based on path rather than slug, seems to let developers create files in more flexible way, especially when their routing depend on file/directory structure, as Theme Docs does.

What do you think on this topic, or what is your original intention to use `slug` to fetch surrounding documents?

[Reproduction Link (Wrong Prev/Next Link) (CodeSandbox)](https://codesandbox.io/s/upbeat-turing-kl7x3?file=/content/category-2/challenge.md)

**Comment by NozomuIkuta** [comment]
@sts-ryan-holton 

Oops, I missed the word `help` in the path passed to `$content()` and the demo app. 💦 
But, I know you can fix it. 🥇

**Comment by sts-ryan-holton** [comment]
@NozomuIkuta thanks for that! Your implementation works extremely well for my use case! One more thing if I may...

Given my directory listing for my articles:

```
content/
├─ help/
│  ├─ account/
│  │  ├─ introduction.md
│  │  ├─ all-about-accounts.md
│  ├─ domains/
│  │  ├─ introduction.md
│  │  ├─ all-about-domains.md
│  ├─ monitors/
│  │  ├─ introduction.md
│  │  ├─ all-about-monitors.md
```

I'd like to display a count for each of the articles within each directory on my page that lists out all of the available categories...

The page that lists them out has this...

```javascript
async asyncData ({ $content }) {
  const guides = await $content('help', { deep: true })
                        .fetch()
  return {
    guides
  }
}
```
And the way I'm displaying my "categories" is by using a `v-for` on my page, and simply checking using a `v-if` whether the `slug` equals **introduction**, if it does, then I display that (there's probably a cleaner, faster way to display the categories), but within my `v-for` I'd like to display a count of say the number of articles, minus the **introduction** for everything within the `monitors` directory, in the above case there's just one file, but I'll be adding more. My thinking is that I'd need to somehow fetch all of the articles on a per category basis and check this?

FYI...

Each of my articles contains a custom `category` tag that I've given them, this is how I'm determining the link structure, for example:

```md
---
title: Managing your monitors
category: monitors
---
```

**Comment by NozomuIkuta** [comment]
@sts-ryan-holton 

If I understand what you mean correctly, you want to show like this, don't you?

```markdown
<!-- Each list item is a link to introduction page -->
- Category 1 (1)
- Category 2 (2)
```

If so, taking a look at how Theme Docs renders its left sidebar will be helpful.

First, Theme Docs fetches all the pages and group them by `category` property defined in the front matter ([code](https://github.com/nuxt/content/blob/5fe0e7643c0ead96ff7f91bdb20c0a7d809adae6/packages/theme-docs/src/store/index.js#L73-L85)).
Second, Theme Docs iterates the object, where key is `category` and value is an array of documents, with nested `v-for` ([code](https://github.com/nuxt/content/blob/5fe0e7643c0ead96ff7f91bdb20c0a7d809adae6/packages/theme-docs/src/components/app/AppNav.vue#L11-L40)).

Here is [a simplified demo (CodeSandbox)](https://codesandbox.io/s/laughing-greider-do844?file=/pages/_category/_slug.vue).

Note that Theme Docs guarantees the order of categories and pages by defining `position` in each document and setting a `sortBy()` query when fetching.

By the way, you might want to refer to [Fetching content](https://content.nuxtjs.org/fetching) page of the official site, so that you will come up with a variety of ways of fetching as you want.

**Comment by sts-ryan-holton** [comment]
Thanks for that! I'll take a look in due course and see what I can come up with! @NozomuIkuta
