### ISSUE TITLE
How to exclude/ignore README.md from $content() fetches?

### ISSUE THREAD

**Issue by katerlouis** [nuxt/content#643]
I'm wondering if I can tell @nuxt/content to ignore README files when "fetching" data in a cms like manner.

`this.$content('menues')`  and `http://localhost:3030/_content/menues` both also return the `README.md` in `~/content/menues/`

I don't want that. 
I'd like to exclude README files in general for all content fetches.

**Comment by NozomuIkuta** [comment]
@katerlouis 

`where()` query-building method is for you ([doc](https://content.nuxtjs.org/fetching#wherequery)).

Each file name is used as a built-in `slug` property of document in database ([doc](https://content.nuxtjs.org/writing)), which means it can be filtered out by `where()` method like the following:

```javascript
$content().where({ slug: { $ne: 'README' } }).fetch()
```

If you want to fetch all the `README.md` files only from all the sub directories, you can also do it:

```javascript
$content({ deep: true }).where({ slug: { $eq: 'README' } }).fetch()
```

---

JFYI:

Actually, you can chain query-building methods before calling `fetch()`, so that you can fetch only documents which match all the queries built in the chain.

For example, here is how Theme Docs fetches prev/next documents of the current page's document ([code](https://github.com/nuxt/content/blob/96d0504590e0968eba7f90cbe60c2704c50e9b9a/packages/theme-docs/src/pages/_.vue#L58-L62)):

```javascript
const [prev, next] = await $content(app.i18n.locale, { deep: true })
      .only(['title', 'slug', 'to'])
      .sortBy('position', 'asc')
      .surround(document.slug, { before: 1, after: 1 })
      .fetch()
```

**Comment by katerlouis** [comment]
Thanks a lot! 
I knew about the chaining and figured this could be done with `.where()`, but didn't quite get how to say "where slug NOT equals 'README'" – gotta google these mongo shorthands.

Now to the master question. Is there a way to make this the default behavior, so I don't need to write this all the time? I don't see why I would ever fetch the README on this site.

**Comment by NozomuIkuta** [comment]
@katerlouis 

Unfortunately, there is no such option to achieve your goal.

Actually, I created an issue (#595) to request such feature. 

As a result of discussion, `draft: true/false` flag at document level is introduced to Theme Docs, by the author ([commit](https://github.com/nuxt/content/commit/f67ec7de49db6d49692d836e1d09f944e33da52f)).

You may be able to achieve your goal by wrapping `$content()` by yourself in some way.

Here is a [demo app](https://codesandbox.io/s/shy-firefly-zwx77?file=/pages/index.vue), in which `$content` is wrapped by another function and the wrapper is injected to `context` via plugin system of Nuxt.

**Caveat: Not-well tested, just a proof of concept.**

---

By the way, I agree with your idea which matches DRY principle.
It would be nice of Nuxt Content to provide a way to create _instances_ [like axios does](https://github.com/axios/axios#axioscreateconfig).

**Comment by farnabaz** [comment]
Ignoring specific content is supported in nuxt/content@v2. https://content.nuxtjs.org/guide/writing/content-directory#ignoring

Closing this because nuxt/content@v1 will not receive and update for this
