### ISSUE TITLE
Caching content

### ISSUE THREAD

**Issue by schneefux** [nuxt/content#664]
Hi,

I am running my Nuxt website behind a CDN which reduces page load time by caching responses. Static content as served by this API is a good candidate for that.
Unfortunately, responses from the content API are not cacheable because the query builder always sends a HTTP POST request:
https://github.com/nuxt/content/blob/f5b3cf7dc73db3d6de9827c58e713501f68f6f84/packages/content/templates/query-builder.js#L100
POST cannot (should not) be cached. GET should be used for read access to data.
I've seen that the backend middleware already has an implementation to read query parameters from GET requests:
https://github.com/nuxt/content/blob/f5b3cf7dc73db3d6de9827c58e713501f68f6f84/packages/content/lib/middleware.js#L34
Is it possible to switch the request method to GET by default?
In addition to that, I'd like to set `Cache-Control: public, max-age=1234` so that the CDN and the browser can keep the response in cache for a while.

**Comment by adrianrudnik** [comment]
Same issue here, the POST is uncacheable and will always fallback to the origin server, even the actual response will never vary if the same query is sent on subsequent requests.

Maybe create a repeatable hash for the qurey builder and attach it as a cache-busting GET-variable on the query itself?

**Comment by adrianrudnik** [comment]
Just to get a bit more thought into it beforehand: The reason a POST is done is because we need to submit a nested JSON for filtering correct? Something like

```json
{"deep":false,"text":false,"sortBy":[{"date":"desc"}],"limit":4}
```

Wouldn't it be the simplest solution to just switch to GET and just engrave the query into the path (base64+urlencode), like

```POST /_content/artikel``` becoming
```GET /_content/artikel/eyJkZWVwIjpmYWxzZSwidGV4dCI6ZmFsc2UsInNvcnRCeSI6W3siZGF0ZSI6ImRlc2MifV0sImxpbWl0Ijo0fQ%3D%3D```

even with complex filters we should never near the ~2000 url max length for some systems and the response/url is never important to SEO.

By not using a query string other systems will handle it as a static resource (some CDNs do cache differently when they detect a query string). Cloudflare would still not cache the resource unless "Cache Everything" or another rule is defined on `/_content/*` but thats fine I guess.

Nuxt could also answer the requests with a proper 'cache-control: public, max-age=31536000' header like it does for other static assets as it would be essentially become one.

That all is under the following assumptions (and I'm very new to nuxt/content):
- Responses from  /_content/* is idempotent based on the URL (or query right now) on a built page.
- It is assumed that a cache purge must be done after deploying a new built (or an additional built/content hash must be engraved into the generated GET url)
- There is no new attack vector as it's as easy to send a GET request as it is to send a POST to the `/_content` endpoints.
- The responses are not client specific.

Not sure if that simple switch wouldn't be all that is needed.

**Comment by farnabaz** [comment]
This enhancement already done in the nuxt/content@v2 and all the requests are GET and cacheable.
