### ISSUE TITLE
[docs-theme] different Github repo link (edit link)

### ISSUE THREAD

**Issue by divine** [nuxt/content#689]
### Is your feature request related to a problem? Please describe.

There are times when you have a split documentation and code repository in the organization.

Currently, there is no possibility to define a different Github URL which can change 'Edit this page on GitHub' link which is linking to the correct repository.

### Describe the solution you'd like

I'd like 'defaultGithub' setting to define another repository which will change 'Edit this page on GitHub' link.

Thanks!

**Comment by Geminii** [comment]
Hi @divine 👋 

Currently the doc theme is limited because we can't override component behavior. 
Related to #328 it will be possible into the next version 😀

**Comment by divine** [comment]
Hi @Geminii!

Any ETA for new doc theme release? i have just checked up that issue and related PRs everything looks merged.

Feel free to close this issue since it became a question not a feature request :)

Thanks!

**Comment by Geminii** [comment]
Doc theme will be extract of this repository but there is no estimation date for the moment. 
Maybe @Atinux could give you an approximative date about this ?

**Comment by NozomuIkuta** [comment]
@divine 

If I understand you correctly, are your goals to fetch releases from a repository and to direct edit links to another repository?

If so, you can do it with theme-docs v0.6.0+. ([doc link](https://content.nuxtjs.org/themes/docs#properties)).

```json
// settings.json
{
  "github": "https://github.com/nuxt/content",
  "githubApi": "https://api.github.com/repos/nuxt/nuxt.js"
}
```

The usage is not described in official doc, because these settings are originally implemented for GitHub Enterprise repositories, where API root differs from version to another (e.g. `https://domain.com/api/v3/{org}/{repo}/releases`). 

If you feel it hacky, actually I agree with you. 

It would be better if we have more refined setting schema (maybe when the theme reaches to v1.0? 🤔).

**Comment by divine** [comment]
> @divine
> 
> If I understand you correctly, are your goals to fetch releases from a repository and to direct edit links to another repository?

Hi @NozomuIkuta!

Yes, exactly. I've changed to your provided example settings and everything works and looks great!

Thanks again!
