### ISSUE TITLE
[ANNOUNCEMENT] The Docs Theme is moving away...

### ISSUE THREAD

**Issue by benjamincanac** [nuxt/content#726]
Hello Nuxt community!

First of all, I would like to thank everyone of you for the keen interest you have shown towards @nuxt/content and its peers. All your feedback and help through pull requests has been much appreciated.

This issue's goal is to announce that in a near future (next few weeks), @nuxt/content-theme-docs will move to its own repository with lots of improvements and a new name: **Docus**.

You can have a preview of the new design at https://tailwindcss.nuxtjs.org.

Some pending pull requests have been merged to the docs-theme but we will stop merging new ones as we have to backport all of your hard work to Docus.

A last release will be made next week preceding the release of Docus.

Thanks again, I hope you'll all enjoy the new theme 💚 

---

EDIT (31/05/2022):

The **@nuxt/content-theme-docs** is being replaced by **Docus**.

You can learn more about the Docus project [here](https://nuxtlabs.com/docus).

The release date is scheduled during VueJS Amsterdam 2022.

Once released, this issue will be closed and Docus will become the main recommendation to create documentations.

Stay tuned for more updates 💚

**Comment by NozomuIkuta** [comment]
Sorry for asking stupid question, but how should I pronounce the word _Docus_?
Is it short form of _documentaries_  (i.e. /dɒkjʊs/) ?

**Comment by derHodrig** [comment]
Could you give us the option to simply change the brandings? Or is it possible to fork the theme and edit on our own?

**Comment by ArsalaBangash** [comment]
I've just started using the docs 

> Could you give us the option to simply change the brandings? Or is it possible to fork the theme and edit on our own?

I was wondering about that as well because I would love to be able to add Discord and Gitlab icons

**Comment by ArsalaBangash** [comment]
> Could you give us the option to simply change the brandings? Or is it possible to fork the theme and edit on our own?

I think a found a solution here: https://nuxtjs.blog/customization/components#overriding-components

**Comment by derHodrig** [comment]
@ArsalaBangash it seems it wont work with components in components/app/AppHeader.vue for example. I changed the Logo layout and even wrote some stuff, just to see the changes. There where no changes.
But I am not sure, if the docs-theme uses nuxt components, i think yes.... but it will not replace it. Did you got it to work?

**Comment by ArsalaBangash** [comment]
> @ArsalaBangash it seems it wont work with components in components/app/AppHeader.vue for example. I changed the Logo layout and even wrote some stuff, just to see the changes. There where no changes.
> But I am not sure, if the docs-theme uses nuxt components, i think yes.... but it will not replace it. Did you got it to work?

Experimenting today and I'll update you :)

**Comment by ArsalaBangash** [comment]
@derHodrig You're right. Couldn't get it to work :( #774

**Comment by philschmid** [comment]
Since there is no offical repository yet. I really like the rework! well done! but. code "`code`" is not formatted as expected.
I expected `@nuxtjs/tailwindcss` to look like that and not on the screenshot.

![image](https://user-images.githubusercontent.com/32632186/107873166-b0890000-6eb0-11eb-91c1-aa60388ecb23.png)

**Comment by derHodrig** [comment]
Any Updates on this announcment?

**Comment by psto** [comment]
@derHodrig AFAIK [docus ](https://docus.dev/) is not official yet, but alpha should be announced the following week.

**Comment by dadaocongsanvietnam** [comment]
Any Updates on this announcment?

**Comment by jaydrogers** [comment]
Is there any sort of timeline or expectation for Docus?

We love Nuxt Content, and we're absolutely stoked for Docus. It's going to be next level!

But not seeing a commit on Nuxt Content since March 2nd and leaving Docus as "soon" (without any clear expectation of what that means) is a little nerve racking 😅

I know you guys are hard at work, but showing a little bit of an update from your side will go a long way 🙌

**Comment by Atinux** [comment]
Hi everyone and sorry for the delay, after a lot of weeks of work into Docus, we will soon open an alpha with the repo  once we finish the documentation.

Docus will not be open source during alpha and we will setup a public repo to gather your feedbacks 😊 

Thank you so much for your patience.

**Comment by geomagilles** [comment]
Any update on the timeline :)?

**Comment by ArsalaBangash** [comment]
If anyone is looking for an intermediary solution between nuxt-content-docs and docus, I'd like to suggest trying out [grey-docs](https://grey-docs.grey.software/), a nuxt content docs theme fork with upgrades including support for TailwindV2 

[I created a PR that adds a page for it on the themes category of the nuxt content website](https://github.com/nuxt/content/pull/962)

**Comment by stewones** [comment]
updates ? 😬

**Comment by jaydrogers** [comment]
Docus is currently accepting beta registrations: https://docus.com/

Allegedly it will be available this month 😅🤞 https://twitter.com/docus_/status/1447987133680136194

**Comment by jaydrogers** [comment]
So I know there are a lot of people who have been anxiously awaiting the release of Docus for months and we're still in the same spot from before. Its release has been stuck at "soon" and that's as much as we'll ever know until its beta is released.

How far are we from that point? Only the Nuxt Team knows that.

As a community, we can't get mad or upset. The Nuxt Team has been hard at work on many other things and it's incredible to see what these guys have been building. **Let us not forget, this is open source 😃**

At the end of the day, there are a number of us that are unsure what do do at this point. From my personal perspective, we literally have a handful of open source projects stuck in a holding pattern until we deploy some sort of documentation engine with it (Docus is hands down the most promising solution).

I am sure we're not the only ones in this situation.

## What this post is all about

I'm interested to hear the thoughts of others who find themselves in this similar situation. I'd just like to bounce ideas to figure out what's the best thing to do at this point.

Here are the options that I see. I am interested to hear from others if they know more or have feedback:

#### Use Nuxt Content
Nuxt Content is what brought us here. We absolutely love it. It's the best documentation experience to date. The major reason why we've been so excited about Docus is the ability for a ton of customizations. It seems like Docus will fix all of our customization needs.

#### Reverse engineer Docus
Nuxt released [v3.nuxtjs.org](https://v3.nuxtjs.org/) using Docus. You can [find the code on Github](https://github.com/nuxt/framework/tree/main/docs) and see Docus working in action. This looks extremely promising, and probably can be figured out with some reverse engineering. It does come with downfalls though:

- You're completely swimming at your own risk
- You could spend hours reverse engineering when things could dramatically change by the beta release

#### Use Docasaurus
Obviously finding another solution like [Docasaurus](https://docusaurus.io/) is always on the table, but the Nuxt Content experience was so beautiful, it would be really hard to walk away from a great Nuxt community.

#### Wait
Of course... I guess we can always stick to "Plan A" and just wait for "soon" to be something, someday. 😅

## Moving forward
I hope the community finds this post as a postive discussion about options moving forward. I'm genuinely curious to hear what others think and I hope nothing in this post is taken with snarkiness or negativity in any way.

To the Nuxt Team: Thanks for everything you do and your hard work. Can't wait to check out Docus, no matter when it is released. ❤️

**Comment by shellen** [comment]
@jaydrogers I would love to have a bare-bones `nuxt-content` to use until Docus is ready for primetime. I started a new project on Nuxt 3 without checking to see if it would be supported and assumed. Ass = me. However, I love `nuxt-content` and is part of the reason I gravitated towards Nuxt in the first place. If I could vote, I would ask for a version of `nuxt-content` for now and will gladly explore Docus in the near future.

**Comment by stewones** [comment]
We want nuxt content 😛

**Comment by jaydrogers** [comment]
Just an update on this (for anyone in the same position), this is what we are doing after some research. 

We evaluated:

1. Running Nuxt Content (works, but limited customization capabilities)
2. Deploying Docusaurus (React based... not for us)
3. Forking the v3.nuxtjs.org site (which is [currently running Docus](https://github.com/nuxt/framework/tree/main/docs), but could change dramatically in the future)

After spending a few days on this, **we went with running Nuxt Content for now** because:

- The URL structures in Nuxt Content are similar to what Docus will be (saving us the headache of 301 redirects if we switch to Docus)
- Nuxt Content is documented and stable, saving us hours on reverse engineering alpha software that isn't officially released
- Nuxt Content has a simple experience where we can collaborate with others on our open source documentation
- Nuxt Content supports automatic sitemap.xml generation

Where Nuxt Content is lacking:
- There is not a documented method on how to customize the header or footer
- There is no way to have full customization of the homepage. You're expected to follow a strict template
- The writing experience can get confusing when you are managing a lot of content (you have to modify the "front matter" in a ton of different places)

Thankfully Docus will solve all these issues above. The experience and structure seems incredible! You can see it in their repo: https://github.com/nuxt/framework/tree/main/docs/

Docus will be the superior choice for us once it is stable, but until we get any official word on it, I guess it's back to "Plan A" and just wait 😃

We expect the "Nuxt Content → Docus" migration to take some effort, but we believed it was more important to get our open source tools out there than wait for a release that wasn't in our control. 

I hope our experience helps others finding themselves in a similar spot. I definitely want to extend a huge "thank you" to the Nuxt Labs team for all their efforts. 🙌

**Comment by justindasilva** [comment]
Oh how I wish that a beta of Docus would be released sometime soon :)

**Comment by Tahul** [comment]
> Oh how I wish that a beta of Docus would be released sometime soon :)

It's done!

https://docus.dev

https://github.com/nuxt-themes/docus

Thank you all for following, I'm closing this one now, feel free to report issues on Docus repository! 😄
