### ISSUE TITLE
"Unwrapping" content into a CSS grid

### ISSUE THREAD

**Issue by SirWindfield** [nuxt/content#793]
Content loaded through Nuxt-content gets wrapped inside two divs: `nuxt-content-container` and `nuxt-content`. The latter then contains the elements of the markdown file. Is it somehow possible to "unpack" those, making them direct decendents of the HTML instead of having them be wrapped in the divs? 

The reason why I want this is to get more control over how I arrange the content inside a parent CSS grid. Since the complete document is wrapped inside the divs, I can't re-arrange the markdown elements properly (I know that `display: contents` works, but the coverage in browsers isn't great so far).

Instead of this:
```html
<!-- This div wraps <nuxt-content /> -->
<div class="grid ...">
  <div class="nuxt-content-container" data-v-f58a9f50="" data-v-dac74cd4="">
    <div class="nuxt-content" data-v-f58a9f50="">
      <!-- I want to align these paragraphs (e.g. the markdown content) to the grid -->
      <p>Some paragraph </p>
      <p>Some paragraph </p>
    </div>
  </div>
</div>
```

I'd need this:
```html
<!-- This div wraps <nuxt-content /> -->
<div class="grid ...">
      <p>Some paragraph </p>
      <p>Some paragraph </p>
</div>
```

**Comment by NozomuIkuta** [comment]
@SirWindfield 

Currently, there is no way to unwrap them.
The 2 _div_ elements are hard-coded in the source code.

https://github.com/nuxt/content/blob/ebaedede5935f597fe325322ef57f09f6222e1ff/packages/content/templates/nuxt-content.js#L152-L154

https://github.com/nuxt/content/blob/4ba67b4522f11db97ec2f8c161bd2aa98655db37/packages/content/templates/nuxt-content.dev.vue#L2

While NuxtContent (prod) component is a functional component and could return an array (i.e. fragment), NuxtContent (dev) is a stateful component that must have only one root element to wrap editor component and NuxtContent (prod) component. 

This limitations is not due to Nuxt Content, but Vue 2.x. When Nuxt 3 (i.e. Vue 3) is released, we would be able to achieve what you want.

**Comment by NozomuIkuta** [comment]
@SirWindfield 

One more point, did you try use  [deep-selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) already?
With this, you may be able to achieve your goal.

**Comment by SirWindfield** [comment]
That should work with setting the grid start/end points. The problem that I have is that the whole document is added as a single row inside the grid. What I'd like to do is to have each element in the markdown file (images (`img`), paragraphs (`p`), tables (`table`)) in its own row.

**Comment by SirWindfield** [comment]
Just for others if they stumble across this: I've decided to go with `display: contents`, as the only serious bugs across today's browsers are related to the `role` attribute not being propagated properly (which in my use-case doesn't really matter).

Example SCSS:
```scss
.nuxt-content-container {
    display: contents;
    
    .nuxt-content {
        display: contents;
        & > * {
            grid-column-start: 4;
        }
    }
}
```
