### ISSUE TITLE
Object 'description' field is not allowed in json ext 

### ISSUE THREAD

**Issue by teonji** [nuxt/content#798]
### Version
@nuxt/content: v1.13.1
nuxt: v2.15.2

### Steps to reproduce
Just install @nuxt/content and put in content folder a json with description field as object 
eg.
```json
{
  "id": 1,
  "slug": "test",
  "description": {
    "text": "hello!"
  }
}
```

### What is Expected?
Nothing special, just works like other fields.

### What is actually happening?
With description field i got this error when start project.
Changing `description` with `_description` issue disappear.

I need to use a specific structure with `description` field as an object and not a string, how can i do that?
I also tried to config plugin with fullTextSearchFields: ['slug'] but i can't skip fullTextSearchFields in fullTextSearchFields if field is custom like that.

![image](https://user-images.githubusercontent.com/1690632/109274599-fb413b00-7813-11eb-993c-9944d823e153.png)

**Comment by NozomuIkuta** [comment]
This is not a bug but rather a spec of [LokiDB](https://github.com/LokiJS-Forge/LokiDB), which is internally used as database of nuxt content.

Nuxt content configures it via `fullTextSearchFields` option, in which properties (i.e. fields) of _documents_ LokiDB should search a text, when `search()` method is called in a query chain. By default, according to [official documentation](https://content.nuxtjs.org/configuration#fulltextsearchfields), `fullTextSearchFields` is set as `['title', 'description', 'slug', 'text']`.

LokiDB expects values of these properties are string or number that can be converted to string ([link](https://github.com/LokiJS-Forge/LokiDB/blob/ccc45527b2e9ce639987cf46c8ff53c7bb8a406a/packages/full-text-search/src/full_text_search.ts#L54-L60)). 

Since there is no flexibility to change this behavior (e.g. setting dot-notation like `'description.text'`), all we can do is to override `fullTextSearchFields` option for `'description'` not to be searched.

```javascript
// nuxt.config.js
export {
  content: {
    fullTextSearchFields: ['title', 'slug', 'text']
  }
}
```

**Comment by teonji** [comment]
Ok sorry, i didn't know that.
Yeah, if is possibile should be great!
