### ISSUE TITLE
[create-nuxt-content-docs] PostCSS error

### ISSUE THREAD

**Issue by felixoi** [nuxt/content#826]
I followed the documentation on https://content.nuxtjs.org/themes/docs#getting-started and used `npx create-nuxt-content-docs <project-name>`. I'm not sure if this is related to the warning `postcss@8.2.8 is installed but ^7.0.32 is expected`. Even if it is, I did not choose PostCSS 8 explicitly, so this must be a bug in the template.

### Version
@nuxt/content-theme-docs: 0.10.1
nuxt: 2.15.2

### Reproduction Link
https://github.com/felixoi/nuxt-content-bug

### Steps to reproduce
Run `npm run dev`

### What is Expected?
PostCSS should work fine

### What is actually happening?
PostCSS error:
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js. (repeated 20 times)

**Comment by shrawanx** [comment]
Hi,
Any updates on this?

Is this the reason, the UI was completely broken?

**Comment by Feuerhamster** [comment]
Same problem here.
I got a lot of ` WARN  You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js. ` in my console after a fresh installation, and the UI is completely broken.

**Comment by NozomuIkuta** [comment]
@Atinux 

Hi, sorry to bother you.

Impact of this issue is so large, and I saw people who seem to be facing at the issue (i.e. closed issues above) during triage.

To be honest , it would be good of the core team to share your situation and/or attitude to this issue.
It enables people to make decisions (e.g. wait for fixes, search for another solution for now), or make them "relieved" somehow, which I believe better at least than leaving it without any information.

I guess you and the team are hardworking for Nuxt 3 and migrating official modules to it.
So, IMHO, it is also acceptable to tell people to wait for Docus and Nuxt Content v2, instead of fixing the current version.

By the way, setting this issue pinned would help people find this issue and avoid creating duplicated one.

--- 

P.S. 

I'm sorry I couldn't find the root cause of the bug, and too busy right now to dig into in this time. 🙏 😢 
As far as I saw, the contents of `node_modules` after `npm install` and `yarn install` were different, but I couldn't find why.

**Comment by NozomuIkuta** [comment]
@felixoi 

How did you "pin" versions of packages?
Only PostCSS?

```json
{
  "resolutions": {
    "postcss": "^7.0.32"
  }
}
```

**Comment by felixoi** [comment]
@NozomuIkuta With yarn I did not have to pin it, it worked out of the box. I haven't figured out an npm solution yet.

**Comment by NozomuIkuta** [comment]
P.S.

I posted the message above at midnight, so proofreading and double-checking is appreciated. 🙏

**Comment by Atinux** [comment]
I agree to downgrade to fix the issue @NozomuIkuta, can you open a PR for it and ping me?

We are working hard to release Docus that will take the lead for the Docs theme.

**Comment by NozomuIkuta** [comment]
@Atinux 

I have submitted a PR!
Please check it out. 🙏
