### ISSUE TITLE
Generating pages more than one level deep fails

### ISSUE THREAD

**Issue by jhull** [nuxt/content#84]
Nuxt 2.12, Content 1.2

`npm run generate` works great when it's a single level folder within `content` like these:

```
/content
  /articles
  /posts
  /blog
```

All the content under articles, posts, and blog generate as expected.

When it's more than one level deep `/articles/series` - there is an `Error generated` issue for those pages, along with the `_slug` files within them.

The fetch line is simply:

```
    async fetch () {
      this.seriesOfArticles = await this.$content('articles/series').sortBy('published', 'desc').fetch()
    }
```

And it works fine locally - just when I try to generate it fails.

**Comment by benjamincanac** [comment]
Hey @jhull,

Could you provide a reproduction link?

**Comment by mathieunicolas** [comment]
I just posted this : https://github.com/nuxt/content/issues/57#issuecomment-638400106
In an other issue, maybe this can help for the repro ?

**Comment by jhull** [comment]
Closed before I had a chance to address this...but the issue was that I had a folder structure like this:

```
/content
  /articles
  /posts
  /courses
  /intro-class
```
and tried to generate routes like this:

```
 const introClasses = await $content('intro-class').only(['path']).fetch()
```

which failed because the route for `intro-class` was at `/courses/intro-class`. It worked great when `npm run dev` when accessed at `site://courses/intro-class`, but when trying to generate Content assumed the `content` folder structure was also the structure of the routes...

Once I dragged the `/intro-class` folder into `/courses` the route generation worked well. It might be good to add a notice that the `content` directory must match the assumed routes, so that others don't run into the same problem.

**Comment by benjamincanac** [comment]
Hey @jhull,

Actually, `content` does not need not match the routes of your site. You can do whatever pages you want and whatever content structure.

It would be easier with a reproduction link, but your problem might be related with `nuxt generate` as dynamic routes are ignored because Nuxt does not know what these routes will be. You can check the [Nuxt generate documentation](https://nuxtjs.org/api/configuration-generate#routes).

Here is also a link on how to use [Nuxt Content with generate](https://content.nuxtjs.org/advanced#static-site-generation).
