### ISSUE TITLE
Lose responsiveness when using a code block in markdown

### ISSUE THREAD

**Issue by TheFoolishPupil** [nuxt/content#849]
Not sure if this is an issue with Nuxt Content, but figured I would post it here to see if there was anyone who could lend a hand. I am using Nuxt Content in conjunction with Tailwind typography. My rendered markdown page works as expected and is fully responsive at different view ports. Upon adding a code block however, I lose the responsiveness. Try to have a look at the video.

https://user-images.githubusercontent.com/43202406/113850639-f79dbe00-979a-11eb-934b-4f33f5cf4c34.mov

**Comment by TheFoolishPupil** [comment]
Ah I should mention the issue seems to stem from the contents of the code block itself. So if the code block are shorter than the current width of the parent element, it can shrink down until the code fills the entire element, and then does not overflow to scroll.

**Comment by TheFoolishPupil** [comment]
I have tried using a vue component in my markdown to see if I can narrow down the cause of the issue. I have the same issue when I emulate the markdown rendering as the first image below.
<img width="145" alt="Screenshot 2021-04-07 at 15 25 21" src="https://user-images.githubusercontent.com/43202406/113873968-99320900-97b5-11eb-9368-bef257047681.png">
In the next image you can see I have removed the code element and insert the text directly into the pre element. With this the page remains responsive as desired.
<img width="134" alt="Screenshot 2021-04-07 at 15 28 14" src="https://user-images.githubusercontent.com/43202406/113874243-e0b89500-97b5-11eb-8db0-5996837d4021.png">

**Comment by TheFoolishPupil** [comment]
Found the culprit. My _<Nuxt>_ element had the class _flex_; Upon removal I have the desired responsiveness.

**Comment by seabothsides** [comment]
Im having the same problem, what Nuxt element had the flex attribute?

**Comment by r-token** [comment]
I was having this issue as well, and, like @TheFoolishPupil, it was caused by `flex` on my main layout template.

Removing `flex` wasn't really an option for my layout though. So, if you need to keep `flex` active, the fix for this is to set `min-width: 0` on the same level.

I'm using Tailwind CSS here, but this is what my fix looked like:

<img width="793" alt="flex-solution" src="https://user-images.githubusercontent.com/5607449/178648085-76ce74aa-b45c-40d5-9f9a-b12e9b512af3.png">

There's a good blog post on this [here](https://weblog.west-wind.com/posts/2016/feb/15/flexbox-containers-pre-tags-and-managing-overflow).

**Comment by mrepol742** [comment]
this is helpful thank you
