### ISSUE TITLE
Opt out of automatic nuxt-link for linking to static content

### ISSUE THREAD

**Issue by ishitatsuyuki** [nuxt/content#851]
### Is your feature request related to a problem? Please describe.

All links that start with a '/' are replaced with nuxt-link. This makes it impossible to link to some file in the `static` directory.

### Describe the solution you'd like

There should be an option to opt out of autolinking, either as a new component, a tag, or a syntax modification to the link.

**Comment by ManasMadrecha** [comment]
You may choose normal `a href` tag for things that don't want a nuxt-link. 🤷🏻‍♂️

**Comment by ishitatsuyuki** [comment]
If you try it you will see it’s forced and doesn’t work.
Offending code here: https://github.com/nuxt/content/blob/35718b99fcc581073ea14afd6a7b5f16dbca9051/packages/content/parsers/markdown/compilers/json.js#L16

**Comment by ManasMadrecha** [comment]
Yes, your issue is logical.

I typed this is one of my md files `<nuxt-link to="/README.md">file</nuxt-link>` to link to the default readme file in static folder. It goes to correct URL, i.e. `http://localhost:3000/README.md`, but shows only the dynamic page which I have in my project. Only on actually clicking reload, I can see the actual readme file.

So, now I tried with <a href="/README.md">file</a> and it gives the same result. So, yes, it doesn't work.

Anyway, I think Content module is not meant for opening md files in static folder, when you have a Content folder for that. 🤔 For some specific files in static folder, like for images, you can use nuxt-img and for PDFs you can use vue-pdf-app.

**Comment by ManasMadrecha** [comment]
@ishitatsuyuki 

I tried adding a `target="_blank"` attribute and now it works.

**Comment by btkostner** [comment]
Why was this closed? This seems pretty unintuitive that could be improved by looking at the url to see if it includes an extension.

**Comment by btkostner** [comment]
In the mean time, here is a fix I've been using to undo the `nuxt-link` for static files:

```js
import { extname } from 'path'

function maybeFixLink (node) {
  if (node.tag === 'nuxt-link') {
    const ext = extname(node.props.to)

    if (ext !== '') {
      node.tag = 'a'
      node.props.href = node.props.to
      node.props.rel = ['nofollow', 'noopener', 'noreferrer']
      node.props.target = '_blank'

      delete node.props.to
    }
  }

  if (node.children != null) {
    node.children.forEach(maybeFixLink)
  }
}

export default function (document) {
  if (document.extension !== '.md') {
    return
  }

  document.body.children.forEach(maybeFixLink)
}
```

then just put it on the `content:file:beforeInsert` like so:

```js
import linkFixes from './link-fixes.js'

export default {
  hooks: {
    'content:file:beforeInsert': linkFixes
  }
}
```

Working example here: https://github.com/system76/docs/blob/master/modules/link-fixes.js

**Comment by schnetzi** [comment]
I am having the same issue and I don't understand why this was closed.

@btkostner thanks for your "temporary" fix.
