### ISSUE TITLE
Option to use path in slug generation

### ISSUE THREAD

**Issue by VaZark** [nuxt/content#860]
### Is your feature request related to a problem? Please describe.

When creating articles, sometimes they might have the title but since they are placed in different subdirectories under `content`, the filesystem will naturally not throw a name conflict error. However, when the url is directly called, the system will select only the latest one. I'd like to ensure that subdirectories or tags can be added to the slug generation to enforce uniqueness

```
content
 | -- django
       |-- basics.md --> http://localhost:3000/basics
 | -- java
       |-- basics.md --> http://localhost:3000/basics
```

### Describe the solution you'd like

The slug generation can allow an option to use the path to the file as a part of the slug or each subfolder can have a default config.json that can be used to store the alias to be used instead of the complete directory path.

## The options

With subdirectory as slug
```
content
 | -- django
       |-- basics.md --> http://localhost:3000/django/basics
       |-- advanced
            |-- orm_issues --> http://localhost:3000/django/advanced/orm_issues
 | -- java
       |-- basics.md --> http://localhost:3000/java/basics
       |-- advanced
            |-- orm_issues.md --> http://localhost:3000/java/advanced/orm_issues
```

With alias config
```
content
 | -- django
       |-- basics.md --> http://localhost:3000/django/basics
       |-- advanced
            |-- orm_issues --> http://localhost:3000/django/orm_issues
       |-- config.json ({"alias":"django"})
 | -- java
       |-- basics.md --> http://localhost:3000/basics
       |-- advanced
            |-- orm_issues.md --> http://localhost:3000/advanced_java/orm_issues
            |-- config.json ({"alias":"advanced_java"})
```

**Comment by tdwells90** [comment]
Isn't this something you can do with the `deep` flag? For example:

```javascript
const allContent = await this.$content('/', { deep: true })
```

**Comment by ManasMadrecha** [comment]
You can easily do this:
1. Create a dynamic `_.vue` page. Here, fetch all your posts inside Content folder using `where` option with `path` query. You may use regex too for better querying, if your `_.vue` page is inside some other page. Of course, you need to choose `{deep:true}` too
2. For automatic route generation, add a list of children on this `_.vue` page. 
   - For dynamic pages to work properly, in your Content folder, you need to have a md file and a folder of same name. So, these children will be the children files of the current post, based on the Content folder. 
   - Now, to fetch a list of children, you can do this by fetching a new array of all posts filtered using `where` option with `dir` query.
   - Where you want to show this list of children is up to you. I usually prefer having it in a Left sidebar, with right Sidebar showing my table of contents.
3. Due to step 2 fetching, all your children (i.e. all your posts) will now have automatically generated routes, and these routes will have URL based on path. 😄

**Comment by VaZark** [comment]
That sounds feasible. I'll try it out and update the ticket. 

However, having a default `useContentPathAsSlug` option alongside `deep` so that the module uses the same value for slug that is used by path seems like a far simpler setup. I raised the request as path-based slug routing sounds like a common use case. 

I'll see if I can hack around and submit a PR.

**Comment by ManasMadrecha** [comment]
Routing is based on automatic route generation, which has nothing to do with Content module. Whatever nuxt-link based URLs will be present anywhere in `pages` or `md files`, those routes will be generated.

You want your post's slug to be used as path. Basically, what you want is a structure to present your posts in such a way that path-based URL is generated for every post. And for that, you have `_.vue` dynamic page feature, which is a Nuxt feature, and not Content feature.

### Three strategies

Content already gives us both `slug` and `path` properties. Suppose you are not using `_.vue` dynamic page and you are simply creating normal `blog-index` page to list all your posts. Now, you can fetch all your posts, and display them. But where do you want each post to link depends on you. 
1. If each md file has unique file name, then you can use `slug` directly. 
2. But if you do not have unique file name, then you can add a `slugurl` property inside the yaml frontmatter of each md file (as I did in my first Nuxt content project) and use this `slugurl` (which is SEO-based) to link the article to.
3. What if you don't want to add manually a unique `slugurl`? Then you can use `path` which will always be unique for each md file.

So, basically what link of the post will be generated depends on how you list them inside `pages` folder's `blog-index` page. It doesn't depend on `Content` folder. 😮

To want same value for slug as path is absurd, because we already have slug and path as two separate properties. Now what you want to use for linking purpose is entirely up to you. 😄 

### Fetch individual post

Now, how will you fetch an individual post for each of the above 3 strategies?
1. For 1st option, you can directly create a `_slug.vue` page and use `where` option on `slug : $route.params.slug`. 
   1. As each post has unique file name, so slug will be unique for each post. 
   2. Also, on the `blog-index` page, you used slug as the link for each post; so clicking on any link from that index page will properly land you on individual post.
2. For 2nd option, similarly, you can create `_slugurl.vue` page and use using `where` option on `slugurl : $route.params.slugurl`. 
   1. Further logic same as above option 1. 
3. For 3rd option, you can create a dynamic page. Now as the blog-index's links sends you to `https://website.com/folder/subfolder/post`, you need cannot use `params.somedynamic` in individual post fetching. Here, a dynamic page `_.vue` comes to the rescue, on which query using `where` on {path : $route.params.pathMatch}.

### Logical conclusion

As you can see, what should be as URL of a post depended on what links were used in `blog-index` page, and not how the post was fetched individually. What link you want to use on `blog-index` page depends on you (either path or slug). You have both options (rather 3 options, as stated more above). Enjoy 🙏🏻🚀

**Comment by tdwells90** [comment]
@VaZark I don't think a PR is necessary, as the `deep` flag already provides you with what you need. The issue you're facing is likely with your folder structure.

For example, you could have a folder structure like this:

```
/pages
  /topic
    /_topic
      _slug.vue
```
And then, in your `_slug.vue` file:

```javascript
asyncData({ $content, params }) {
  const postLink = `${params.topic}/${params.slug}`
  const post = await $content(topicLink).fetch()
  return { post }
}
```
This will return the content at that relative path in your content folder.

**Comment by VaZark** [comment]
Thanks for your input everyone. I finally decided to follow with @tdwells90 's idea of explicit nesting of folders

The final page structure is:

```
/pages
  _slug.vue
  /_topic
    _slug.vue
    /_subtopic
      _slug.vue
```
with the `_slug.vue`s having:

```js
async asyncData({ $content, params }) {
  const currentFolder = // populated with '' or params.topic or params.topic/params.subtopic based on directory
  const article = await $content(currentFolder, params.slug).fetch() // added {deep:true} only for subtopic
  return { article }
}
```
