### ISSUE TITLE
sortBy not sorting numerical values properly

### ISSUE THREAD

**Issue by ElnuDev** [nuxt/content#945]
### Version
@nuxt/content: 1.14.0
nuxt: 2.15.7

### Steps to reproduce

Use `sortBy` on a field such as `slug` on some content that has numerical values.

### What is Expected?

When filtering by a field with numbers involved, the sorting method should take numbers into consideration. For example, if one is filtering by `slug` on a set of files with numerical file names going from 1 to 25 (i.e. `1.md`, `2.md`, `3.md`, etc.), the order of slugs being outputted should be:

`1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`.

### What is actually happening?

`1`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `2`, `20`, `21`, `22`, `23`, `24`, `25`, `3`, `4`, `5`, `6`, `7`, `8`, `9`

**Comment by lustremedia** [comment]
@ElnuDev the issue here is that sortBy uses a direction 'asc' or 'desc'. So on numeric values it converts to string and then asc or desc on the those strings ...

here is the code:
[https://github.com/nuxt/content/blob/939caf36c547a6b4af6e303c52ed5989a5dea2f0/packages/content/templates/query-builder.js#L36 ](url)

**Comment by NozomuIkuta** [comment]
@ElnuDev @lustremedia 

Every property of _document_ object is a string.

https://github.com/nuxt/content/blob/0b6a7be6f6287cde880b0d37c88e6461efa167ff/packages/content/types/content.d.ts#L6-L13

You _parse_ slugs or markdown files as numbers, but that's just because you are a human, not a computer.
I believe it's reasonable to assume that slugs are string, so that Nuxt Content can simplify the situation.

**Comment by ElnuDev** [comment]
A lot of file sorters do take numbers into account, even in file names that aren't just numeric and have other text in them. I don't know about Windows and macOS (I'd assume they do something similar), but on Linux the Nautilus file explorer properly handles sorting numeric values in file names. I don't see why Nuxt Content can't do something similar.

**Comment by supermanzer** [comment]
I even created an integer component in the front matter for each page I wanted sorted and still I get the text behavior.  I'm guessing this is because it is stored as text and sorted prior to being parsed into text and numeric data.

I'm trying to built out a calendar with Nuxt content and this is not making life easy.

**Comment by farnabaz** [comment]
This will not going to implement in Content V1, But it is already supported in Content V2. https://github.com/nuxt/content/issues/1074

I'm closing this issue in favor Content V2 and new sort syntax.
