### ISSUE TITLE
Fetch elements in the random order

### ISSUE THREAD

**Issue by radoslawkalamon** [nuxt/content#984]
Hi!

Is it possible with `nuxt/content` to fetch elements in random order?

I would like to fetch items to the related articles section and just pick 2-3 random articles from category.

**Comment by NozomuIkuta** [comment]
@radoslawkalamon 

At the moment, such feature is not natively supported.

IMO, Nuxt Content should be "pure" and returns same results for same input.
Otherwise, we can't unit-test the functionality.

---

For your reference, here are some approaches that I came up with.

One approach is to get all the related posts and then randomize the array (e.g. by `lodash.shuffle()`).
This would be simplest. But, the more related posts there are, the more time it take to fetch and randomize.

Another approach is to randomize Nuxt Content's numerical queries (i.e. [`limit()`](https://content.nuxtjs.org/fetching#limitn), [`skip`](https://content.nuxtjs.org/fetching#skipn), and [`surround`](https://content.nuxtjs.org/fetching#surroundslugorpath-options)).
In this approach, the result may be empty depending on queries are set, so you have to handle such cases.

**Comment by NozomuIkuta** [comment]
Oh, you don't have to randomize the array fetched.
You can just pick up some out of the array like `array[Math.floor(Math.random() * myArray.length)]`.

**Comment by radoslawkalamon** [comment]
@NozomuIkuta: This is exactly what I have done in the my app - first fetch all posts, then pick random elements like this:
```javascript
return (await $content(query).fetch())
  .sort(() => 0.5 - Math.random())
  .slice(0, quantity)
```
Thanks for your answer! I'm closing the ticket.

---

No native options for a randomized fetch. Yep, that a bummer :/
