### ISSUE TITLE
Edit this page on GitHub button link breaks often

### ISSUE THREAD

**Issue by sanamiy** [nuxt/content#991]
### Version
@nuxt/content: v1.15.1
nuxt: 2.15.3
@nuxt/content-theme-docs: v0.11.1

### Reproduction Link
[https://pwa.nuxtjs.org/](https://pwa.nuxtjs.org/)
[https://github.com/nuxt-community/pwa-module/tree/main/docs](https://github.com/nuxt-community/pwa-module/tree/main/docs)

### Steps to reproduce
**Edit this page on GitHub** button links always break when create a document site with `@nuxt/content-theme-docs`  and the `/content` folder is directory belongs to the main directory.   **`~/content/*.md`**

case of failure: [https://pwa.nuxtjs.org/](https://pwa.nuxtjs.org/)
broken Edit this page on GitHub link: 
[https://github.com/nuxt-community/pwa-module/edit/master/docs/content/en/index.md](https://github.com/nuxt-community/pwa-module/edit/master/docs/content/en/index.md)

on the other hand,  if `/content` folder is under `docs` folder the link do not break.
**`~/docs/content/*.md`**
case of success:[https://content.nuxtjs.org/](https://content.nuxtjs.org/)
Edit this page on GitHub link: [https://github.com/nuxt/content/edit/main/docs/content/ja/index.md](https://github.com/nuxt/content/edit/main/docs/content/ja/index.md)

### What is actually happening?

the string in links _/docs_ is the cause of this bug.
The string in links _/docs_ should be option.
or if the option already exists, please tell me.

Thank you,

**Comment by NozomuIkuta** [comment]
@sanamiy 

Thank you for reporting an issue.

It seems that both cases, failure and success, result in NOT FOUND error.
Would you elaborate your situation a little bit more?

**Comment by sanamiy** [comment]
sorry, I’ve pasted wrong links in success case, so I corrected that.
The edit button in docs of @nuxt/content is ok.

**Comment by NozomuIkuta** [comment]
@sanamiy 

Thank you for fixing the sample. 🙌 

Actually, URL to edit a file can be configured via options: `defaultBranch` and `defaultDir`, [as written in documentation](https://content.nuxtjs.org/themes/docs#properties).

FYR, here is the code:

https://github.com/nuxt/content/blob/b97cf549577cb8ded2ecb3400aaa8e0fb9845f89/packages/theme-docs/src/components/app/AppPageBottom.vue#L33-L46

---

By the way, in this time, it's not because of `defaultDir` why the link to edit PWA module documentation is broken.
It's because `defaultBranch` is wrong. 

Nuxt core team renamed the default branch of their repositories from `master` to `main` a while ago.
But it seems that they didn't fix Theme Docs option.

I will check and fix other module documentation as needed.
Again, thank you for reporting! :+1:

**Comment by NozomuIkuta** [comment]
Here is one thing to correct.

> Nuxt core team renamed the default branch of their repositories from master to main a while ago.
> But it seems that they didn't fix Theme Docs option.

I noticed that `main` branch is default value of Theme Doc.
So they didn't have to fix Theme Doc option when they change the default branch of the repositories.

The fact seems to be that PWA module documentation is not up-to-date. 🤔 
I confirmed that the link is correct in my local environment.

I will open an issue in PWA module repository (as well as keeping checking other documentation).

**Comment by NozomuIkuta** [comment]
Oh, you already created one.
Thank you so much! 🙌 

https://github.com/nuxt-community/pwa-module/issues/500

**Comment by sanamiy** [comment]
Thank you so much, nozumuIkuta!
Problems were all solved by `defaultBranch` and `defaultDir` options!
I confirmed that  in docs of pwa module  problems was not caused by dir but by branch.
Thank you for telling me ☺️

**Comment by danieldevine** [comment]
> as written in documentation

Ironically, this link is 404. Is this documentation still available somewhere?
